export const supplementalKaplanSocialStudiesGroups = [
  {
    id: "kaplan-ss-1",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 1,
    questionEnd: 1,
    rangeLabel: "Kaplan Social Studies · Question 1",
    contextType: "graph",
    marker: "Question 1 is based on the following paragraph and graph.",
    context: "When the value of exported goods is greater than the value of imported goods, there is a favorable balance of trade. When imports are greater than exports, there is an unfavorable balance of trade.\n\nU.S. Merchandise Imports and Exports, 2000–2010. The graph compares U.S. imports and exports in millions of dollars and shows imports above exports throughout the period.",
    sourcePages: [1, 1],
    visualPage: 4001,
    questions: [{ number: 1, text: "Which of the following statements is supported by the paragraph and the graph?" }],
  },
  {
    id: "kaplan-ss-2",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 2,
    questionEnd: 2,
    rangeLabel: "Kaplan Social Studies · Question 2",
    contextType: "table",
    marker: "Question 2 is based on the following table. You may use your calculator.",
    context: "Gallup opinion poll: percentage identifying as independent during the first six months of 2013.\n\nJanuary 38%; February 38%; March 36%; April 40%; May 39%; June 41%.",
    sourcePages: [2, 2],
    visualPage: 4002,
    questions: [{ number: 2, text: "During the first six months of 2013, what percent of the people surveyed, on average, considered themselves independents? Assume that the same number of people were surveyed each month. Round your answer to the nearest percentage." }],
  },
  {
    id: "kaplan-ss-3-4",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 3,
    questionEnd: 4,
    rangeLabel: "Kaplan Social Studies · Questions 3–4",
    contextType: "map",
    marker: "Questions 3 and 4 are based on the following information and map.",
    context: "Gross domestic product (GDP) per capita is found by adding the value of all goods and services produced in a country in a year and dividing by the number of people living there. The map shows GDP per capita for countries around the world in 2008.",
    sourcePages: [3, 4],
    visualPage: 4003,
    questions: [
      { number: 3, text: "In the map above, place a dot on the continent that, in 2008, had the highest percentage of countries with a GDP per capita of less than $10,000 per year." },
      { number: 4, text: "Place the countries below in order from highest GDP per capita to lowest GDP per capita: Democratic Republic of Congo, United States, Mexico, India." },
    ],
  },
  {
    id: "kaplan-ss-5",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 5,
    questionEnd: 5,
    rangeLabel: "Kaplan Social Studies · Question 5",
    contextType: "table",
    marker: "Question 5 refers to the following information and table.",
    context: "The Consumer Price Index (CPI) measures the average prices paid by consumers for a typical assortment of goods and services. A higher CPI indicates that prices have risen.\n\nCPI percent change over the previous year: 2008 3.8; 2009 −0.4; 2010 1.6; 2011 3.2; 2012 2.1.",
    sourcePages: [4, 4],
    visualPage: 4004,
    questions: [{ number: 5, text: "For the years included in the table, what was the median percent change in CPI over the previous year?" }],
  },
  {
    id: "kaplan-ss-6",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 6,
    questionEnd: 6,
    rangeLabel: "Kaplan Social Studies · Question 6",
    contextType: "timeline",
    marker: "Question 6 refers to the following information and timeline.",
    context: "The Fifteenth Amendment, ratified in 1870, declared that U.S. citizens’ right to vote could not be denied on account of race. The Voting Rights Act of 1965 outlawed poll taxes and literacy tests and established protections for minority voters.",
    sourcePages: [5, 5],
    visualPage: 4005,
    questions: [{ number: 6, text: "On the timeline above, place two dots above the years in which voting rights were expanded in the United States." }],
  },
  {
    id: "kaplan-ss-7",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 7,
    questionEnd: 7,
    rangeLabel: "Kaplan Social Studies · Question 7",
    contextType: "passage",
    marker: "Question 7 is based on the following paragraph.",
    context: "The ancient Greeks and ancient Chinese both thought that a sound political system and well-established social relationships were necessary for a stable society. Greek rule was decentralized, while Chinese rule was largely centralized; the two civilizations valued different structures and institutions.",
    sourcePages: [5, 5],
    visualPage: null,
    questions: [{ number: 7, text: "Based on the paragraph, what did the ancient Greeks and the ancient Chinese have in common in regard to politics and government?" }],
  },
  {
    id: "kaplan-ss-8",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 8,
    questionEnd: 8,
    rangeLabel: "Kaplan Social Studies · Question 8",
    contextType: "table",
    marker: "Question 8 refers to the following chart.",
    context: "The Effect of World War II on Industry. The chart compares manufacturing output and corporate profits before and after taxes, showing large increases during the war period.",
    sourcePages: [5, 6],
    visualPage: 4005,
    questions: [{ number: 8, text: "Which of the following best explains why the war had the effect on industry indicated by the chart?" }],
  },
  {
    id: "kaplan-ss-9",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 9,
    questionEnd: 9,
    rangeLabel: "Kaplan Social Studies · Question 9",
    contextType: "passage",
    marker: "Question 9 refers to the following paragraph.",
    context: "The U.S. president has great influence over foreign policy because international relations can require quick and decisive action. During a foreign crisis, the public usually rallies to the president’s support, at least initially.",
    sourcePages: [6, 6],
    visualPage: null,
    questions: [{ number: 9, text: "Which of the following values probably underlies Americans’ initial approval of a president’s emergency foreign policy actions?" }],
  },
  {
    id: "kaplan-ss-10",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 10,
    questionEnd: 10,
    rangeLabel: "Kaplan Social Studies · Question 10",
    contextType: "passage",
    marker: "Question 10 refers to the following passage.",
    context: "The Sherman Antitrust Act of 1890 made it illegal to monopolize or conspire to monopolize an industry or restrain trade. Because courts interpreted its broad language inconsistently, Congress passed the Clayton Antitrust Act in 1914 to target specific anticompetitive actions.",
    sourcePages: [6, 7],
    visualPage: null,
    questions: [{ number: 10, text: "In the passage above, the writer’s main point is that" }],
  },
  {
    id: "kaplan-ss-11",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 11,
    questionEnd: 11,
    rangeLabel: "Kaplan Social Studies · Question 11",
    contextType: "passage",
    marker: "Question 11 refers to the following passage.",
    context: "The passage argues that unchecked carbon emissions have contributed to climate change, whose hazards include droughts, diminishing freshwater supplies, and decreased world food production. It says the United States should reduce industrial emissions and support alternative fuels, while noting that the Environmental Protection Agency has fostered international partnerships.",
    sourcePages: [7, 8],
    visualPage: null,
    questions: [{ number: 11, text: "Place the letter of each statement within the correct column: The author would agree, the author would disagree, or the author does not address the information. A. The United States has failed to take any action against carbon emissions. B. The dangers of climate change are more significant than the possible benefits. C. Wind energy is preferable to solar energy. D. Climate change will not impact the world food supply." }],
  },
  {
    id: "kaplan-ss-12-13",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 12,
    questionEnd: 13,
    rangeLabel: "Kaplan Social Studies · Questions 12–13",
    contextType: "map",
    marker: "Questions 12 and 13 refer to the following map.",
    context: "Forced Resettlement of American Indians, 1830s. The map shows tribal home territories in the eastern United States and the designated Indian Territory to the west, connected by routes of forced removal.",
    sourcePages: [9, 10],
    visualPage: 4009,
    questions: [
      { number: 12, text: "Which of the following is the most likely reason that American Indians were forcibly relocated in the 1830s?" },
      { number: 13, text: "Which American Indian tribe was moved the farthest from its tribal lands?" },
    ],
  },
  {
    id: "kaplan-ss-14",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 14,
    questionEnd: 14,
    rangeLabel: "Kaplan Social Studies · Question 14",
    contextType: "figure",
    marker: "Question 14 refers to the following cartoon.",
    context: "A 1989 political cartoon contrasts the treatment of a voter with the treatment of a special-interest group by members of Congress.",
    sourcePages: [10, 10],
    visualPage: 4010,
    questions: [{ number: 14, text: "With which of the following opinions would the cartoonist be most likely to agree?" }],
  },
  {
    id: "kaplan-ss-15",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 15,
    questionEnd: 15,
    rangeLabel: "Kaplan Social Studies · Question 15",
    contextType: "passage",
    marker: "Question 15 refers to the following passage.",
    context: "In the late 1800s, industrialization caused large-scale migration from rural to urban areas. Families lost the support of extended relatives, and children became more of an economic drawback in cities than they had been on farms; the birthrate dropped and average family size shrank.",
    sourcePages: [11, 11],
    visualPage: null,
    questions: [{ number: 15, text: "Which of the following is the best summary of this passage?" }],
  },
  {
    id: "kaplan-ss-16-17",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 16,
    questionEnd: 17,
    rangeLabel: "Kaplan Social Studies · Questions 16–17",
    contextType: "table",
    marker: "Questions 16 and 17 refer to the following chart.",
    context: "Acts of Parliament Directed at the American Colonies: the Sugar Act of 1764, Quartering Act of 1765, Stamp Act of 1765, Declaratory Act of 1766, and Townshend Acts of 1767. The acts imposed duties, required support for soldiers, regulated documents, asserted Parliament’s authority, and imposed import duties.",
    sourcePages: [11, 12],
    visualPage: 4011,
    questions: [
      { number: 16, text: "How did the Declaratory Act differ from all the other acts of Parliament shown in the chart?" },
      { number: 17, text: "The information in this chart would have been most useful for the writing of which of the following documents?" },
    ],
  },
  {
    id: "kaplan-ss-18-19",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 18,
    questionEnd: 19,
    rangeLabel: "Kaplan Social Studies · Questions 18–19",
    contextType: "map",
    marker: "Questions 18 and 19 are based on the following map.",
    context: "Percentage of Undernourished People Worldwide. The map uses ranges from 0% to 4%, 4% to 20%, 20% to 35%, and 35% to 73%, along with a no-data category.",
    sourcePages: [13, 13],
    visualPage: 4013,
    questions: [
      { number: 18, text: "According to the map, what is the percentage range of people in the United States who do not get enough food and nutrients?" },
      { number: 19, text: "Which of the following statements is supported by the information on the map?" },
    ],
  },
  {
    id: "kaplan-ss-20-22",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 20,
    questionEnd: 22,
    rangeLabel: "Kaplan Social Studies · Questions 20–22",
    contextType: "table",
    marker: "Questions 20 through 22 refer to the following chart.",
    context: "Important Political Documents Preceding the Declaration of Independence and the U.S. Constitution: Magna Carta (1215), Mayflower Compact (1620), Petition of Right (1628), Great Fundamentals (1636), and English Bill of Rights (1688). The chart summarizes how these documents limited authority, established self-government, and granted rights.",
    sourcePages: [14, 15],
    visualPage: 4014,
    questions: [
      { number: 20, text: "What do the Mayflower Compact and the Great Fundamentals have in common?" },
      { number: 21, text: "One major grievance the American colonists had against the British was taxation without representation. By which of the following documents were the writers of the Declaration probably most influenced as they drafted their list?" },
      { number: 22, text: "Which document first set limits on the British monarch’s powers?" },
    ],
  },
  {
    id: "kaplan-ss-23",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 23,
    questionEnd: 23,
    rangeLabel: "Kaplan Social Studies · Question 23",
    contextType: "passage",
    marker: "Question 23 refers to the following passage.",
    context: "The civil rights movement inspired historians to reinterpret slavery’s impact on U.S. society and African Americans. Some historians emphasized slavery’s destructive effects, while others argued that enslaved people overcame hardship by developing a unique African American culture with strong religious and musical traditions.",
    sourcePages: [15, 16],
    visualPage: null,
    questions: [{ number: 23, text: "Based on the paragraph, which of the following statements is an opinion rather than a fact?" }],
  },
  {
    id: "kaplan-ss-24-25",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 24,
    questionEnd: 25,
    rangeLabel: "Kaplan Social Studies · Questions 24–25",
    contextType: "graph",
    marker: "Questions 24 and 25 refer to the following paragraph and graph.",
    context: "The market price of a product tends to change in a way that brings supply and demand into balance, a condition called equilibrium. The graph shows supply and demand for apples and their equilibrium point.",
    sourcePages: [16, 17],
    visualPage: 4017,
    questions: [
      { number: 24, text: "According to this graph, what is the market price of apples, also known as the price at equilibrium?" },
      { number: 25, text: "Which of the following would result if part of the apple crop were destroyed but demand remained the same?" },
    ],
  },
  {
    id: "kaplan-ss-26",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 26,
    questionEnd: 26,
    rangeLabel: "Kaplan Social Studies · Question 26",
    contextType: "map",
    marker: "Question 26 refers to the following paragraph and map.",
    context: "The Battle of Fort Sumter was the first battle of the American Civil War. South Carolina seceded before the battle; after President Lincoln called for volunteers, four additional states seceded. The map shows the progress of secession.",
    sourcePages: [18, 19],
    visualPage: 4018,
    questions: [{ number: 26, text: "Match each state to the appropriate column: belonged to the Confederacy before the Battle of Fort Sumter or belonged to the Confederacy after the Battle of Fort Sumter. Use Iowa, North Carolina, Delaware, and Alabama." }],
  },
  {
    id: "kaplan-ss-27-29",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 27,
    questionEnd: 29,
    rangeLabel: "Kaplan Social Studies · Questions 27–29",
    contextType: "diagram",
    marker: "Questions 27 through 29 refer to the following paragraph and diagram.",
    context: "Most cases arising under federal law are tried in the federal court system. The diagram shows several levels of courts and routes by which cases may be appealed to a higher court, including district courts, the U.S. Courts of Appeals, the Supreme Court, the Court of International Trade, and other specialized courts.",
    sourcePages: [19, 20],
    visualPage: 4019,
    questions: [
      { number: 27, text: "A U.S. import-export firm files a lawsuit against a foreign trading company. In which court is the suit most likely to be filed?" },
      { number: 28, text: "The U.S. Constitution established only the Supreme Court, but it gave Congress the power to create inferior federal courts. Which of the following is the most likely reason that Congress established other federal courts?" },
      { number: 29, text: "If cases are not resolved in any of the lower federal courts, to which court may they eventually, finally be appealed?" },
    ],
  },
  {
    id: "kaplan-ss-30",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 30,
    questionEnd: 30,
    rangeLabel: "Kaplan Social Studies · Question 30",
    contextType: "figure",
    marker: "Question 30 refers to the following poster.",
    context: "A World War I poster says “WAKE UP AMERICA!” and calls on “EVERY MAN WOMAN & CHILD” to participate in the war effort.",
    sourcePages: [20, 22],
    visualPage: 4021,
    questions: [{ number: 30, text: "Which of the following opinions is the artist attempting to propagate?" }],
  },
  {
    id: "kaplan-ss-31-32",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 31,
    questionEnd: 32,
    rangeLabel: "Kaplan Social Studies · Questions 31–32",
    contextType: "map",
    marker: "Questions 31 and 32 refer to the following paragraph and maps.",
    context: "Mapmakers use projections to represent Earth’s curved surface on flat paper. All projections involve distortion. The Mercator and interrupted projections shown here have different advantages and disadvantages.",
    sourcePages: [22, 23],
    visualPage: 4022,
    questions: [
      { number: 31, text: "Approximately where is there the least distortion on these projections?" },
      { number: 32, text: "A sailor who wanted to plan an around-the-world sailing trip decided to use the interrupted projection. What was wrong with his decision?" },
    ],
  },
  {
    id: "kaplan-ss-33",
    section: "Social Studies",
    topic: "World History",
    questionStart: 33,
    questionEnd: 33,
    rangeLabel: "Kaplan Social Studies · Question 33",
    contextType: "map",
    marker: "Question 33 refers to the following paragraph and map.",
    context: "After the Roman Empire reached its greatest extent, emperors consolidated its borders. Land frontiers were vulnerable and received heavy fortifications; rivers and deserts were natural barriers and received light fortifications; major barriers such as oceans needed no defense.",
    sourcePages: [23, 24],
    visualPage: 4024,
    questions: [{ number: 33, text: "Based on the information above, match the appropriate degree of fortification to each part of the frontier on the map. Use Heavy, Light, and None for the land, river, and sea frontiers." }],
  },
  {
    id: "kaplan-ss-34",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 34,
    questionEnd: 34,
    rangeLabel: "Kaplan Social Studies · Question 34",
    contextType: "passage",
    marker: "Question 34 refers to the following paragraph.",
    context: "The Fifth and Fourteenth Amendments state that government shall not deprive anyone of life, liberty, or property without due process of law. The Fifth Amendment protects people from actions of the federal government, while the Fourteenth Amendment protects people from actions of state governments.",
    sourcePages: [24, 25],
    visualPage: null,
    questions: [{ number: 34, text: "What is a main difference between the Fifth and Fourteenth Amendments?" }],
  },
] as const;

const choices = {
  q1: [
    { label: "A", text: "Exports equaled imports at the start of the 2000s." },
    { label: "B", text: "Exports exceeded imports throughout the 2000s." },
    { label: "C", text: "The United States had a favorable balance of trade in merchandise during the 2000s." },
    { label: "D", text: "The United States had an unfavorable balance of trade in merchandise during the 2000s." },
  ],
  q7: [
    { label: "A", text: "Both governed through a hierarchical bureaucracy." },
    { label: "B", text: "Both valued a stable political framework for society." },
    { label: "C", text: "Both had centralized councils." },
    { label: "D", text: "Both had decentralized political systems." },
  ],
  q8: [
    { label: "A", text: "Even before the United States entered the war, corporate profits had increased sharply." },
    { label: "B", text: "Manufacturing output increased by over 50 percent in two years." },
    { label: "C", text: "The war created a huge demand for military equipment and supplies." },
    { label: "D", text: "With men gone to serve as soldiers, more women were employed in factories." },
  ],
  q9: [
    { label: "A", text: "patriotism" },
    { label: "B", text: "imperialism" },
    { label: "C", text: "self-expression" },
    { label: "D", text: "self-sacrifice" },
  ],
  q10: [
    { label: "A", text: "Courts struck down the Sherman Antitrust Act because its broad language made it unconstitutional." },
    { label: "B", text: "Problems with consistently enforcing the Sherman Antitrust Act led to further legislation to prevent monopolies." },
    { label: "C", text: "Monopolies like US Steel, Standard Oil, and the American Tobacco Company successfully avoided prosecution under the Sherman Antitrust Act." },
    { label: "D", text: "The Sherman Antitrust Act ended monopolies like US Steel, Standard Oil, and the American Tobacco Company, but did not prevent new monopolies from arising." },
  ],
  q12: [
    { label: "A", text: "Whites wanted lands in the Kansas and Nebraska territory for settlement." },
    { label: "B", text: "Whites wanted to take over Indian lands in the eastern states." },
    { label: "C", text: "Indians of different tribes wanted to settle in a single Indian territory." },
    { label: "D", text: "Indians in the eastern states wanted to look for gold in the West." },
  ],
  q13: [
    { label: "A", text: "the Sauk/Fox" },
    { label: "B", text: "the Cherokee" },
    { label: "C", text: "the Choctaw" },
    { label: "D", text: "the Seminole" },
  ],
  q14: [
    { label: "A", text: "People shouldn’t have to stand around waiting to see their elected representatives." },
    { label: "B", text: "Senators should pay attention to special interest groups as well as to voters." },
    { label: "C", text: "Special interest groups are treated better than voters by members of Congress." },
    { label: "D", text: "Senators are nicer to their constituents than are members of the House." },
  ],
  q15: [
    { label: "A", text: "Industrialization led to increased urbanization in the late 1800s." },
    { label: "B", text: "City families lost the social support of their extended families back on the farm." },
    { label: "C", text: "Industrialization and urbanization caused many changes in family life in the late 1800s." },
    { label: "D", text: "In the late 1800s, average family size shrank due to the fall in the birthrate." },
  ],
  q16: [
    { label: "A", text: "It did not involve the quartering of British soldiers." },
    { label: "B", text: "It related only to the import of luxury goods." },
    { label: "C", text: "It did not impose direct economic costs on the colonists." },
    { label: "D", text: "It was enacted long after the other acts of Parliament." },
  ],
  q17: [
    { label: "A", text: "The Declaration of Independence, which explained why the colonies broke away from Great Britain." },
    { label: "B", text: "The Articles of Confederation, which established a central government consisting of a congress." },
    { label: "C", text: "The U.S. Constitution, which established the structure of government for the newly independent nation." },
    { label: "D", text: "Washington’s Farewell Address, in which he warned the new nation of policies and practices he thought unwise." },
  ],
  q18: [
    { label: "A", text: "0% to 4%" },
    { label: "B", text: "4% to 20%" },
    { label: "C", text: "20% to 35%" },
    { label: "D", text: "35% to 73%" },
  ],
  q19: [
    { label: "A", text: "All areas with more than 35% of the population undernourished are inland nations." },
    { label: "B", text: "World hunger would disappear if food were distributed more fairly." },
    { label: "C", text: "There are no areas of hunger in Europe or Australia." },
    { label: "D", text: "Hunger is a major problem in many countries in Africa." },
  ],
  q20: [
    { label: "A", text: "Both limited the power of the king." },
    { label: "B", text: "Both granted rights to the nobles." },
    { label: "C", text: "Both established methods of self-government in English colonies." },
    { label: "D", text: "Both applied to the government in England." },
  ],
  q21: [
    { label: "A", text: "the Mayflower Compact" },
    { label: "B", text: "the Petition of Right" },
    { label: "C", text: "the Great Fundamentals" },
    { label: "D", text: "the English Bill of Rights" },
  ],
  q22: [
    { label: "A", text: "the Magna Carta" },
    { label: "B", text: "the Mayflower Compact" },
    { label: "C", text: "the Petition of Right" },
    { label: "D", text: "the English Bill of Rights" },
  ],
  q23: [
    { label: "A", text: "The civil rights movement took place during the middle of the twentieth century." },
    { label: "B", text: "The civil rights movement caused historians to take another look at slavery." },
    { label: "C", text: "Historians debated slavery’s negative effects on slaves and their descendants." },
    { label: "D", text: "Slavery destroyed the culture of the slaves, diminishing their self-respect." },
  ],
  q24: [
    { label: "A", text: "45 cents" },
    { label: "B", text: "30 cents" },
    { label: "C", text: "20 cents" },
    { label: "D", text: "15 cents" },
  ],
  q25: [
    { label: "A", text: "Supply would increase." },
    { label: "B", text: "The market price would remain the same." },
    { label: "C", text: "The market price would go down." },
    { label: "D", text: "The market price would go up." },
  ],
  q27: [
    { label: "A", text: "the United States Claims Court" },
    { label: "B", text: "the United States Court of Appeals" },
    { label: "C", text: "the Court of International Trade" },
    { label: "D", text: "the United States Tax Court" },
  ],
  q28: [
    { label: "A", text: "The justices of the U.S. Supreme Court were not well versed enough in the law to handle all federal cases." },
    { label: "B", text: "The volume and variety of federal cases were too great for a single court to handle." },
    { label: "C", text: "A system of inferior federal courts gave the United States prestige in the eyes of the rest of the world." },
    { label: "D", text: "The Supreme Court’s power to interpret the Constitution was established in Marbury v. Madison." },
  ],
  q29: [
    { label: "A", text: "the Supreme Court of the United States" },
    { label: "B", text: "the United States Courts of Appeals" },
    { label: "C", text: "the Court of Appeals for the Federal Circuit" },
    { label: "D", text: "the Court of Military Appeals" },
  ],
  q30: [
    { label: "A", text: "Americans are not yet part of civilization." },
    { label: "B", text: "The war effort needs the help of everyone, including men, women, and children." },
    { label: "C", text: "Every man, woman, and child should rest in preparation for the war effort." },
    { label: "D", text: "Americans are part of a lazy civilization." },
  ],
  q31: [
    { label: "A", text: "at 60° north and south latitude" },
    { label: "B", text: "at 40° north and south latitude" },
    { label: "C", text: "at 20° north and south latitude" },
    { label: "D", text: "at 0° latitude" },
  ],
  q32: [
    { label: "A", text: "The interrupted projection distorts distances across the continents at midlatitudes." },
    { label: "B", text: "The interrupted projection distorts distances across the oceans." },
    { label: "C", text: "The interrupted projection distorts the shapes of midlatitude land masses." },
    { label: "D", text: "The interrupted projection shows only a few of the world’s oceans." },
  ],
  q34: [
    { label: "A", text: "The Fifth Amendment applies to adults, and the Fourteenth Amendment, to children." },
    { label: "B", text: "The Fifth Amendment applies to due process, and the Fourteenth Amendment, to freedom of speech." },
    { label: "C", text: "The Fifth Amendment applies to the federal government, and the Fourteenth Amendment, to state governments." },
    { label: "D", text: "The Fifth Amendment applies to life, and the Fourteenth Amendment, to liberty." },
  ],
} as const;

type AnswerRecord = {
  number: number;
  groupId: string;
  section: string;
  topic: string;
  reference: string;
  prompt: string;
  choices: readonly { label: string; text: string }[];
  correctLabel: string | null;
  answerLine: string;
  explanation: string;
  sourcePage: number;
};

const groupById = new Map<string, (typeof supplementalKaplanSocialStudiesGroups)[number]>(supplementalKaplanSocialStudiesGroups.map((group) => [group.id, group]));
const promptFor = (groupId: string, number: number) => groupById.get(groupId)?.questions.find((question) => question.number === number)?.text || "";
const makeQuestion = (number: number, groupId: string, choicesFor: readonly { label: string; text: string }[], correctLabel: string | null, answerLine: string, explanation: string, sourcePage: number): AnswerRecord => {
  const group = groupById.get(groupId);
  if (!group) throw new Error(`Unknown Kaplan Social Studies group: ${groupId}`);
  return { number, groupId, section: group.section, topic: group.topic, reference: "Kaplan Social Studies Practice Test", prompt: promptFor(groupId, number), choices: choicesFor, correctLabel, answerLine, explanation, sourcePage };
};

export const supplementalKaplanSocialStudiesQuestions: readonly AnswerRecord[] = [
  makeQuestion(1, "kaplan-ss-1", choices.q1, "D", "D. The United States had an unfavorable balance of trade in merchandise during the 2000s.", "Imports were greater than exports throughout the 2000s. When imports are greater than exports, the balance of trade is unfavorable.", 1),
  makeQuestion(2, "kaplan-ss-2", [], null, "39%", "The independent percentages total 232. Dividing by six months gives about 38.7%, which rounds to 39%.", 2),
  makeQuestion(3, "kaplan-ss-3-4", [], null, "Africa", "The map shows that Africa had the highest percentage of countries with GDP per capita below $10,000.", 3),
  makeQuestion(4, "kaplan-ss-3-4", [], null, "United States, Mexico, India, Democratic Republic of Congo", "The United States has the highest GDP per capita among the four listed countries, followed by Mexico, India, and the Democratic Republic of Congo.", 3),
  makeQuestion(5, "kaplan-ss-5", [], null, "2.1", "The percent changes sorted from least to greatest are −0.4, 1.6, 2.1, 3.2, and 3.8. The middle value is 2.1.", 4),
  makeQuestion(6, "kaplan-ss-6", [], null, "1870 and 1965", "The Fifteenth Amendment expanded voting rights in 1870, and the Voting Rights Act expanded protections in 1965.", 5),
  makeQuestion(7, "kaplan-ss-7", choices.q7, "B", "B. Both valued a stable political framework for society.", "The paragraph states that both civilizations believed a sound political system and well-established social relationships were necessary for a stable society.", 5),
  makeQuestion(8, "kaplan-ss-8", choices.q8, "C", "C. The war created a huge demand for military equipment and supplies.", "The war effort created a large demand for military equipment and supplies, which increased manufacturing output and corporate profits.", 6),
  makeQuestion(9, "kaplan-ss-9", choices.q9, "A", "A. patriotism", "Patriotism helps explain why Americans initially rally around the president during a foreign crisis.", 6),
  makeQuestion(10, "kaplan-ss-10", choices.q10, "B", "B. Problems with consistently enforcing the Sherman Antitrust Act led to further legislation to prevent monopolies.", "The broad language of the Sherman Antitrust Act led courts to interpret it inconsistently, so Congress passed the Clayton Antitrust Act to target specific anticompetitive actions.", 7),
  makeQuestion(11, "kaplan-ss-11", [], null, "A disagree; B agree; C not addressed; D disagree", "The passage says positive efforts are underway, says the hazards of climate change outweigh potential benefits, does not compare wind and solar energy, and identifies decreased food production as a danger.", 7),
  makeQuestion(12, "kaplan-ss-12-13", choices.q12, "B", "B. Whites wanted to take over Indian lands in the eastern states.", "The forced relocation opened eastern tribal lands to white settlement and expansion.", 9),
  makeQuestion(13, "kaplan-ss-12-13", choices.q13, "B", "B. the Cherokee", "The Cherokee were moved from the southeastern United States to the designated Indian Territory farthest west on the map.", 10),
  makeQuestion(14, "kaplan-ss-14", choices.q14, "C", "C. Special interest groups are treated better than voters by members of Congress.", "The cartoon contrasts a special-interest group receiving attention with a voter who is left waiting.", 10),
  makeQuestion(15, "kaplan-ss-15", choices.q15, "C", "C. Industrialization and urbanization caused many changes in family life in the late 1800s.", "The passage connects industrialization and urbanization with changes in family support, children’s economic roles, birthrates, and family size.", 11),
  makeQuestion(16, "kaplan-ss-16-17", choices.q16, "C", "C. It did not impose direct economic costs on the colonists.", "The other acts imposed costs through import taxes, stamps, or the requirement to provide food and shelter for soldiers. The Declaratory Act asserted Parliament’s authority without imposing a direct economic cost.", 12),
  makeQuestion(17, "kaplan-ss-16-17", choices.q17, "A", "A. the Declaration of Independence, which explained why the colonies broke away from Great Britain.", "The acts listed in the chart were grievances that helped justify the colonies’ declaration of independence.", 12),
  makeQuestion(18, "kaplan-ss-18-19", choices.q18, "A", "A. 0% to 4%", "The United States is shaded in the 0% to 4% range on the map key.", 13),
  makeQuestion(19, "kaplan-ss-18-19", choices.q19, "D", "D. Hunger is a major problem in many countries in Africa.", "The map shows that more than 20 African countries have very high percentages of undernourished people.", 13),
  makeQuestion(20, "kaplan-ss-20-22", choices.q20, "C", "C. Both established methods of self-government in English colonies.", "The Mayflower Compact and Great Fundamentals set forth rules and laws for self-government in English colonies.", 14),
  makeQuestion(21, "kaplan-ss-20-22", choices.q21, "D", "D. the English Bill of Rights", "The English Bill of Rights tied the king’s authority to the consent of representatives and listed rights that influenced the colonists’ grievances.", 15),
  makeQuestion(22, "kaplan-ss-20-22", choices.q22, "A", "A. the Magna Carta", "Signed in 1215, the Magna Carta was the first document in the chart to limit the British king’s powers.", 15),
  makeQuestion(23, "kaplan-ss-23", choices.q23, "D", "D. Slavery destroyed the culture of the slaves, diminishing their self-respect.", "This is presented as an interpretation held by some historians, while the other statements describe facts in the paragraph.", 16),
  makeQuestion(24, "kaplan-ss-24-25", choices.q24, "B", "B. 30 cents", "The equilibrium price is where supply and demand intersect. On the graph, that point is 30 cents.", 17),
  makeQuestion(25, "kaplan-ss-24-25", choices.q25, "D", "D. The market price would go up.", "If supply decreases while demand remains the same, buyers compete for fewer apples and the equilibrium price rises.", 17),
  makeQuestion(26, "kaplan-ss-26", [], null, "Before Fort Sumter: Alabama. After Fort Sumter: Alabama and North Carolina.", "Iowa and Delaware never seceded. Alabama seceded before Fort Sumter and remained in the Confederacy afterward. North Carolina seceded after Fort Sumter.", 18),
  makeQuestion(27, "kaplan-ss-27-29", choices.q27, "C", "C. the Court of International Trade", "A lawsuit involving an import-export firm and a foreign trading company would most likely be filed in the Court of International Trade.", 19),
  makeQuestion(28, "kaplan-ss-27-29", choices.q28, "B", "B. The volume and variety of federal cases were too great for a single court to handle.", "The workload and variety of cases made it impractical for one court to handle every federal case.", 20),
  makeQuestion(29, "kaplan-ss-27-29", choices.q29, "A", "A. the Supreme Court of the United States", "The diagram shows the Supreme Court as the highest court of appeal in the federal system.", 20),
  makeQuestion(30, "kaplan-ss-30", choices.q30, "B", "B. The war effort needs the help of everyone, including men, women, and children.", "The poster calls on every man, woman, and child to take action for the World War I effort.", 22),
  makeQuestion(31, "kaplan-ss-31-32", choices.q31, "D", "D. at 0° latitude", "Distortion is greatest near the poles. Along the equator, at 0° latitude, the projections look most like a globe.", 22),
  makeQuestion(32, "kaplan-ss-31-32", choices.q32, "B", "B. The interrupted projection distorts distances across the oceans.", "The interrupted projection cuts ocean areas apart, making it difficult to measure distances on an around-the-world voyage.", 23),
  makeQuestion(33, "kaplan-ss-33", [], null, "Land frontier: Heavy; river frontier: Light; sea frontier: None", "Land frontiers were vulnerable and needed heavy fortifications; rivers were natural barriers and needed light fortifications; oceans required no defense.", 24),
  makeQuestion(34, "kaplan-ss-34", choices.q34, "C", "C. The Fifth Amendment applies to the federal government, and the Fourteenth Amendment, to state governments.", "The passage identifies the governments to which each amendment applies as the main difference between them.", 25),
];
