export const supplementalPrincetonSocialStudiesTest2Groups = [
  {
    id: "princeton-ss-practice-1-2",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 1,
    questionEnd: 2,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Questions 1–2",
    contextType: "passage",
    marker: "Questions 1 and 2 refer to the following interpretation of the U.S. Constitution.",
    context: "The first ten amendments are called the Bill of Rights. The passage explains that the 14th Amendment, adopted in 1868, widened the application of the Bill of Rights by protecting individual citizens’ rights from encroachment by the states. It quotes the amendment’s protections for privileges and immunities, due process, and equal protection.",
    sourcePages: [2, 3],
    visualPage: null,
    questions: [
      { number: 1, text: "Which of the following descriptions of the authors of the amendments to the Constitution is supported by the passage?" },
      { number: 2, text: "All of the following actions by a particular state would violate the 14th Amendment EXCEPT" },
    ],
  },
  {
    id: "princeton-ss-practice-3",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 3,
    questionEnd: 3,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 3",
    contextType: "passage",
    marker: "Question 3 refers to the following statement about Amelia Earhart.",
    context: "The passage describes Amelia Earhart’s first successful Atlantic flight with Captain Manning, the mixed reactions of the British and American press, and the disparaging comments that may have contributed to her decision to tackle her next mission alone.",
    sourcePages: [3, 3],
    visualPage: null,
    questions: [{ number: 3, text: "In the author’s opinion, what factor contributed to Amelia Earhart’s decision to fly alone?" }],
  },
  {
    id: "princeton-ss-practice-4",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 4,
    questionEnd: 4,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 4",
    contextType: "graph",
    marker: "Question 4 refers to the following chart.",
    context: "The chart compares union membership among public-sector and private-sector workers from 2000 through 2009. It includes statements to classify as supported or unsupported by the graph.",
    sourcePages: [4, 5],
    visualPage: 6004,
    questions: [{ number: 4, text: "Determine whether or not each statement is supported by the information in the graph. Classify statements (a)–(e) as Yes or No in order. (a) There were about 7,500,000 public sector union members in 2007. (b) There were about 9,000,000 private sector employees in 2002. (c) There was an increase in both private and public sector union membership from 2006 to 2008. (d) For the years shown, the number of public sector employees peaked in 2009. (e) Combined union membership in both public and private sectors generally decreased from 2000 to 2009." }],
  },
  {
    id: "princeton-ss-practice-5",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 5,
    questionEnd: 5,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 5",
    contextType: "chart",
    marker: "Question 5 refers to the following chart.",
    context: "The employment-change chart compares percentage change from 1988 to 2006 across occupations, including executive, professional, technical, marketing, administrative support, services, agriculture, precision production, and operators.",
    sourcePages: [5, 6],
    visualPage: 6005,
    questions: [{ number: 5, text: "The information in the chart supports the conclusion that from 1988 to 2006 there has been" }],
  },
  {
    id: "princeton-ss-practice-6",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 6,
    questionEnd: 6,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 6",
    contextType: "graph",
    marker: "Question 6 refers to the following chart.",
    context: "The graph compares GDP per capita in Southeast Asia and Sub-Saharan Africa from 1970 through 1995. GDP per capita is defined as the average value of goods and services produced by a country’s citizens in a year.",
    sourcePages: [6, 7],
    visualPage: 6006,
    questions: [{ number: 6, text: "Based on this information, which statement is an OPINION, rather than a fact, about the GDP per capita of these nations?" }],
  },
  {
    id: "princeton-ss-practice-7",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 7,
    questionEnd: 7,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 7",
    contextType: "passage",
    marker: "Question 7 refers to the following quotation.",
    context: "President John Quincy Adams wrote that the North American continent appeared destined by Divine Providence to be peopled by one nation and associated in one federal Union.",
    sourcePages: [7, 7],
    visualPage: null,
    questions: [{ number: 7, text: "The idea that the United States was destined and divinely ordained by God to expand across the entire North American continent is called" }],
  },
  {
    id: "princeton-ss-practice-8-9",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 8,
    questionEnd: 9,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Questions 8–9",
    contextType: "graph",
    marker: "Questions 8 and 9 refer to the following graph.",
    context: "The Comparative Life Expectancy Rates graph compares male and female life expectancy in Japan, Sweden, and the United States.",
    sourcePages: [8, 9],
    visualPage: 6008,
    questions: [
      { number: 8, text: "According to the above graph, a member of which of the following groups is likely to have the shortest life span?" },
      { number: 9, text: "Which statement is the most likely explanation for the differences in life expectancy shown in the graph?" },
    ],
  },
  {
    id: "princeton-ss-practice-10-12",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 10,
    questionEnd: 12,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Questions 10–12",
    contextType: "passage",
    marker: "Questions 10 through 12 refer to the following interpretation of the role of immigrants in American society.",
    context: "The passage describes the United States as a nation of immigrants and a reputed haven for the oppressed and land of opportunity. It also explains that immigrant groups have faced prejudice and discrimination, while legislation and public awareness have sought to make American society more free and equal.",
    sourcePages: [9, 10],
    visualPage: null,
    questions: [
      { number: 10, text: "Which of the following observations about immigration to the United States is supported by the article?" },
      { number: 11, text: "According to the article, people immigrate to the United States because" },
      { number: 12, text: "Which of the following statements is NOT directly supported by the article?" },
    ],
  },
  {
    id: "princeton-ss-practice-13",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 13,
    questionEnd: 13,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 13",
    contextType: "figure",
    marker: "Question 13 refers to the following photo.",
    context: "An 1852 advertisement expresses opposition to foreign pauper labor and foreigners holding office, reflecting nativist opposition to immigration.",
    sourcePages: [11, 11],
    visualPage: 6011,
    questions: [{ number: 13, text: "This 1852 advertisement expresses opposition to “foreign pauper labor” and “foreigners holding office.” With which of the following policies would the writer of this advertisement be likely to disagree?" }],
  },
  {
    id: "princeton-ss-practice-14",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 14,
    questionEnd: 14,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 14",
    contextType: "map",
    marker: "Question 14 refers to the following sources.",
    context: "The sources include the 19th Amendment, which prohibited denying or abridging the right to vote on account of sex, and a suffrage map showing the status of women’s voting rights in the states before August 1920.",
    sourcePages: [12, 13],
    visualPage: 6012,
    questions: [{ number: 14, text: "Which conclusion is best supported by the information in the passage and the map?" }],
  },
  {
    id: "princeton-ss-practice-15",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 15,
    questionEnd: 15,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 15",
    contextType: "passage",
    marker: "Question 15 refers to the following sources.",
    context: "The first source is the Preamble to the U.S. Constitution, which includes the goals of forming a more perfect Union, establishing justice, ensuring domestic tranquility, providing for the common defense, promoting the general welfare, and securing liberty. The second source is the Declaration of Independence, which mentions equality, life, liberty, and the pursuit of happiness.",
    sourcePages: [13, 14],
    visualPage: null,
    questions: [{ number: 15, text: "According to the excerpts provided, which of these principles is mentioned in the Preamble to the Constitution but NOT in the Declaration of Independence?" }],
  },
  {
    id: "princeton-ss-practice-16",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 16,
    questionEnd: 16,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 16",
    contextType: "graph",
    marker: "Question 16 refers to the following graph.",
    context: "The Crisis-Prone Industry Categories graph compares the average number of crises in industry categories from January 2010 through June 2011.",
    sourcePages: [14, 14],
    visualPage: 6014,
    questions: [{ number: 16, text: "According to the graph, which of the following types of industries was LEAST likely to experience a crisis?" }],
  },
  {
    id: "princeton-ss-practice-17-18",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 17,
    questionEnd: 18,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Questions 17–18",
    contextType: "map",
    marker: "Questions 17 and 18 are based on the following map.",
    context: "The population-density map shows the number of people per square mile across the world using ranges from 0–9 to 1,000 or more.",
    sourcePages: [15, 15],
    visualPage: 6015,
    questions: [
      { number: 17, text: "According to the graph, what are the most densely populated continents?" },
      { number: 18, text: "What factors are the most influential in determining population density?" },
    ],
  },
  {
    id: "princeton-ss-practice-19",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 19,
    questionEnd: 19,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 19",
    contextType: "map",
    marker: "Question 19 refers to the following sources.",
    context: "The sources discuss Manifest Destiny, Democratic and Whig views of westward expansion, and a map of U.S. statehood eras and exploration and settlement routes.",
    sourcePages: [16, 17],
    visualPage: 6017,
    questions: [{ number: 19, text: "Which of the following conclusions is most consistent with the excerpts and map?" }],
  },
  {
    id: "princeton-ss-practice-20",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 20,
    questionEnd: 20,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 20",
    contextType: "passage",
    marker: "Question 20 refers to the following quotation.",
    context: "President Abraham Lincoln wrote that a majority held in restraint by constitutional checks and limitations, and changed by popular opinions, is the only true sovereign of a free people.",
    sourcePages: [18, 18],
    visualPage: null,
    questions: [{ number: 20, text: "The above quote most closely describes which of the following forms of government?" }],
  },
  {
    id: "princeton-ss-practice-21",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 21,
    questionEnd: 21,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 21",
    contextType: "passage",
    marker: "Question 21 refers to the following information.",
    context: "The passage concludes that improvements in technology increase production efficiency, product quality, profits, wages, and the overall economy, benefiting both workers and employers.",
    sourcePages: [18, 19],
    visualPage: null,
    questions: [{ number: 21, text: "Which of the following opinions contradicts the above conclusion about improvements in technology?" }],
  },
  {
    id: "princeton-ss-practice-22",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 22,
    questionEnd: 22,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 22",
    contextType: "map",
    marker: "Question 22 refers to the following maps.",
    context: "The maps compare median household income by county in 2009 with unemployment rates across the United States.",
    sourcePages: [19, 20],
    visualPage: 6019,
    questions: [{ number: 22, text: "Based on this data, which conclusion about the U.S. economy is true?" }],
  },
  {
    id: "princeton-ss-practice-23",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 23,
    questionEnd: 23,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 23",
    contextType: "passage",
    marker: "Question 23 refers to the following sources.",
    context: "The sources include Section 1 of the 14th Amendment, Justice Henry Brown’s defense of enforced racial separation in Plessy v. Ferguson, and the Supreme Court’s ruling in Brown v. Board of Education that separate educational facilities are inherently unequal.",
    sourcePages: [20, 22],
    visualPage: null,
    questions: [{ number: 23, text: "Which of the following conclusions is best supported by the passages?" }],
  },
  {
    id: "princeton-ss-practice-24",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 24,
    questionEnd: 24,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 24",
    contextType: "passage",
    marker: "Question 24 refers to the following historical information.",
    context: "The modern cotton gin, patented by Eli Whitney in 1794, made it easier to separate cotton fibers from seeds.",
    sourcePages: [22, 22],
    visualPage: null,
    questions: [{ number: 24, text: "Why was the cotton gin so revolutionary? The cotton gin" }],
  },
  {
    id: "princeton-ss-practice-25",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 25,
    questionEnd: 25,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 25",
    contextType: "passage",
    marker: "Question 25 refers to the following passage.",
    context: "The passage explains that interpreting the U.S. Constitution is complex and uses the 13th Amendment’s prohibition of involuntary servitude to illustrate how changing interpretations affected Congress’s decision to approve the first peacetime draft in 1940.",
    sourcePages: [22, 23],
    visualPage: null,
    questions: [{ number: 25, text: "What conclusion is supported by this statement about the interpretation of the Constitution?" }],
  },
  {
    id: "princeton-ss-practice-26",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 26,
    questionEnd: 26,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 26",
    contextType: "table",
    marker: "Question 26 refers to the following survey.",
    context: "The jury-service survey compares adults overall and adults from households with incomes under and over $40,000. It reports the percentages called for jury duty and the percentages who served.",
    sourcePages: [24, 24],
    visualPage: 6024,
    questions: [{ number: 26, text: "Which of the following statements is supported by the survey on jury service represented in the table?" }],
  },
  {
    id: "princeton-ss-practice-27-29",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 27,
    questionEnd: 29,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Questions 27–29",
    contextType: "passage",
    marker: "Questions 27 through 29 refer to the following information about energy production.",
    context: "The passage compares fossil fuels, nuclear power, and hydroelectric power. Fossil fuels are inexpensive but polluting; nuclear power is inexpensive but produces dangerous by-products; and hydroelectric power is clean but requires access to suitable rivers and can be affected by erosion.",
    sourcePages: [24, 26],
    visualPage: null,
    questions: [
      { number: 27, text: "Which of the following would most likely result in an increase in the use of nuclear power?" },
      { number: 28, text: "What do all three forms of energy production have in common?" },
      { number: 29, text: "Which of the following communities would most likely use hydroelectric power?" },
    ],
  },
  {
    id: "princeton-ss-practice-30",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 30,
    questionEnd: 30,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 30",
    contextType: "figure",
    marker: "Question 30 refers to the following cartoon.",
    context: "The cartoon is titled “The Big Stick in the Caribbean Sea.”",
    sourcePages: [26, 27],
    visualPage: 6026,
    questions: [{ number: 30, text: "The above cartoon depicts which famous American in which major war?" }],
  },
  {
    id: "princeton-ss-practice-31",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 31,
    questionEnd: 31,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 31",
    contextType: "passage",
    marker: "Question 31 refers to the following excerpt from U.S. history.",
    context: "The passage describes environmental destruction during the California gold rush and John Muir’s efforts to persuade President Roosevelt to protect Yosemite Valley as a national park.",
    sourcePages: [27, 27],
    visualPage: null,
    questions: [{ number: 31, text: "Which of the following might describe John Muir’s opinions regarding the California wilderness?" }],
  },
  {
    id: "princeton-ss-practice-32",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 32,
    questionEnd: 32,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 32",
    contextType: "figure",
    marker: "Question 32 refers to the following globe.",
    context: "The globe places four labeled points at different longitudes and asks the learner to list them from west to east.",
    sourcePages: [28, 28],
    visualPage: 6028,
    questions: [{ number: 32, text: "Which of the following lists the points on the globe from west to east?" }],
  },
  {
    id: "princeton-ss-practice-33",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 33,
    questionEnd: 33,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 33",
    contextType: "passage",
    marker: "Question 33 refers to the following geographic situation.",
    context: "Hurricanes most seriously threaten cities along the Atlantic Ocean and Gulf of Mexico coasts.",
    sourcePages: [28, 28],
    visualPage: null,
    questions: [{ number: 33, text: "Hurricanes are most seriously a threat to cities along the coast of the Atlantic Ocean and the Gulf of Mexico. Which city is NOT seriously threatened by hurricanes?" }],
  },
  {
    id: "princeton-ss-practice-34",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 34,
    questionEnd: 34,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 34",
    contextType: "passage",
    marker: "Question 34 refers to the following excerpt from a proclamation.",
    context: "President Abraham Lincoln’s 1862 proclamation states that rebels, their aiders and abettors, people discouraging volunteer enlistments, people resisting militia drafts, and people guilty of disloyal practices could be subject to martial law and trial and punishment by military courts.",
    sourcePages: [29, 30],
    visualPage: null,
    questions: [{ number: 34, text: "Determine whether or not the following statements are supported by the quote above. Classify statements (a)–(d) as Yes or No in order. (a) Felons previously convicted in civilian courts would be subject to court-martial and punishment. (b) Those attempting to suppress rebels and insurgents would be subject to court-martial and punishment. (c) Those resisting the military draft would be subject to court-martial and punishment. (d) Volunteers for the militia would be subject to court-martial and punishment." }],
  },
  {
    id: "princeton-ss-practice-35",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 35,
    questionEnd: 35,
    rangeLabel: "Princeton Social Studies Test 2 · Practice Question 35",
    contextType: "passage",
    marker: "Question 35 refers to the following excerpt from a speech.",
    context: "In August 1974, President Richard Nixon announced that he would resign the presidency effective the next day and that Vice President Ford would be sworn in as president.",
    sourcePages: [30, 31],
    visualPage: null,
    questions: [{ number: 35, text: "The above quote supports the conclusion that, after the Watergate scandal, President Nixon" }],
  },
] as const;

const choices = {
  q1: [
    { label: "A", text: "They were legal scholars." },
    { label: "B", text: "They believed that the government and the church should be united." },
    { label: "C", text: "They believed that the best type of government would have ultimate authority." },
    { label: "D", text: "They were wary of giving the government too much power over individual rights." },
  ],
  q2: [
    { label: "A", text: "a zoning law prohibiting naturalized citizens from operating ethnic restaurants." },
    { label: "B", text: "legislation requiring citizens to pay taxes regardless of their beliefs." },
    { label: "C", text: "a bill requiring children of citizens of a particular ethnic origin to attend separate public schools." },
    { label: "D", text: "sentencing a person accused of murder without a trial." },
  ],
  q3: [
    { label: "A", text: "a love of her country" },
    { label: "B", text: "the public’s ignorance of aviation" },
    { label: "C", text: "the patriotism of the British" },
    { label: "D", text: "a lack of respect by some members of the press for women’s abilities" },
  ],
  q5: [
    { label: "A", text: "an increase in agricultural jobs." },
    { label: "B", text: "more growth in administrative support jobs than in any other occupation." },
    { label: "C", text: "more growth in administrative support jobs than in services and technicians and support jobs combined." },
    { label: "D", text: "less growth in precision production than in professional specialties." },
  ],
  q6: [
    { label: "A", text: "The GDP per capita for Southeast Asia increased substantially during the years given in the graph." },
    { label: "B", text: "The GDP per capita of Southeast Asia was higher than that of Sub-Saharan Africa in 1995." },
    { label: "C", text: "Sub-Saharan Africa is in desperate need of foreign aid in order to sustain its economy." },
    { label: "D", text: "For many years, Southeast Asia and Sub-Saharan Africa had similar patterns of economic growth." },
  ],
  q7: [
    { label: "A", text: "Manifest Destiny." },
    { label: "B", text: "capitalism." },
    { label: "C", text: "imperialism." },
    { label: "D", text: "eminent domain." },
  ],
  q8: [
    { label: "A", text: "Japanese females" },
    { label: "B", text: "Swedish females" },
    { label: "C", text: "American males" },
    { label: "D", text: "Japanese males" },
  ],
  q9: [
    { label: "A", text: "Asian males tend to work more hours per week than do males from other countries." },
    { label: "B", text: "Life expectancy is higher in North American countries." },
    { label: "C", text: "Japan provides free or low-cost health care for all Japanese citizens." },
    { label: "D", text: "There are fewer natural disasters in Japan than there are in other parts of the world." },
  ],
  q10: [
    { label: "A", text: "Americans are always friendly to every group of people making a new home here." },
    { label: "B", text: "Immigrants come to the United States expecting not to find jobs." },
    { label: "C", text: "The United States wants to shed its reputation as a ‘melting pot’ society." },
    { label: "D", text: "Efforts have been made to ensure that America is receptive to immigrants." },
  ],
  q11: [
    { label: "A", text: "the United States offers political stability and economic opportunity." },
    { label: "B", text: "there is a shortage of available land in their countries." },
    { label: "C", text: "American society discourages social mobility." },
    { label: "D", text: "they do not experience political unrest and oppression in their home countries." },
  ],
  q12: [
    { label: "A", text: "There are steps being taken to decrease the amount of bigotry in the United States." },
    { label: "B", text: "People have immigrated to the United States because they were unhappy with life in other countries." },
    { label: "C", text: "People have immigrated to the United States because of the possibility of new opportunities and social mobility." },
    { label: "D", text: "Immigrants make more money after coming to America." },
  ],
  q13: [
    { label: "A", text: "a trade embargo to keep cheap foreign goods out of the United States" },
    { label: "B", text: "a new law that prevents immigration unless the immigrant is rich" },
    { label: "C", text: "a voter registration drive that targets only American-born persons" },
    { label: "D", text: "a constitutional amendment giving new immigrants voting rights" },
  ],
  q14: [
    { label: "A", text: "American women had no legal right to vote in presidential elections before 1920." },
    { label: "B", text: "The 19th Amendment guaranteed full economic and political equality for women." },
    { label: "C", text: "Most Western states had guaranteed full suffrage to women before 1920." },
    { label: "D", text: "Women in Alaska and Hawaii had no voting privileges before 1920." },
  ],
  q15: [
    { label: "A", text: "the desire for freedom" },
    { label: "B", text: "a united defense" },
    { label: "C", text: "the desire for happiness" },
    { label: "D", text: "the equality of all citizens" },
  ],
  q16: [
    { label: "A", text: "education" },
    { label: "B", text: "chemical" },
    { label: "C", text: "hotel" },
    { label: "D", text: "oil refining" },
  ],
  q17: [
    { label: "A", text: "South America and Europe" },
    { label: "B", text: "Asia and North America" },
    { label: "C", text: "Europe and Asia" },
    { label: "D", text: "South America and North America" },
  ],
  q18: [
    { label: "A", text: "climate and geography" },
    { label: "B", text: "race and language" },
    { label: "C", text: "religion" },
    { label: "D", text: "public sanitation and health" },
  ],
  q19: [
    { label: "A", text: "Elected in 1828, President Andrew Jackson was a Democrat who opposed Westward Expansion." },
    { label: "B", text: "Inspired by the principle of Manifest Destiny, President James K. Polk, a Democrat elected in 1845, sought to secure American control of the Southwest after the Mexican-American War." },
    { label: "C", text: "Whig presidents such as William Henry Harrison, elected in 1841, failed to gather support from the American people because of their insistence on Westward Expansion." },
    { label: "D", text: "Many Democrats, including Franklin Pierce, elected in 1853, opposed the Transcontinental Railroad, since it threatened to expand slavery to Western territories." },
  ],
  q20: [
    { label: "A", text: "a constitutional republic" },
    { label: "B", text: "a monarchy" },
    { label: "C", text: "a pure democracy" },
    { label: "D", text: "anarchy" },
  ],
  q21: [
    { label: "A", text: "New technology will cause companies to decrease the size of their workforce in order to cut costs." },
    { label: "B", text: "Product quality increases consumer satisfaction, which leads to greater company profits." },
    { label: "C", text: "When businesses succeed, more money is reinvested into the economy." },
    { label: "D", text: "Efficiency is a key factor in ensuring a business’s success." },
  ],
  q22: [
    { label: "A", text: "All counties with household incomes of $74,000 or more in 2009 had the lowest unemployment rates." },
    { label: "B", text: "Southeastern states generally have a lower median income than Northeastern states." },
    { label: "C", text: "Only Plains states have unemployment rates below 5.0%." },
    { label: "D", text: "Hawaii has a lower rate of employment than Alaska." },
  ],
  q23: [
    { label: "A", text: "In Brown v. Board of Education, the Supreme Court relied on past legal decisions to help shape its ruling." },
    { label: "B", text: "Plessy v. Ferguson upheld the 14th Amendment’s guarantee of ‘equal protection’ under the law." },
    { label: "C", text: "Brown v. Board of Education upheld the doctrine of ‘separate but equal.’" },
    { label: "D", text: "Brown v. Board of Education found that ‘separate but equal’ facilities were a violation of the 14th Amendment." },
  ],
  q24: [
    { label: "A", text: "caused the massive growth of the wool industry in America." },
    { label: "B", text: "caused the economic destruction of rural farmland." },
    { label: "C", text: "ended the need for slavery." },
    { label: "D", text: "caused the expansion of the cotton industry in the American South." },
  ],
  q25: [
    { label: "A", text: "A document that needs amendments is not a reliable guide for government policy." },
    { label: "B", text: "A document that can be reinterpreted is not an adequate method for resolving legal questions." },
    { label: "C", text: "A text that causes controversy does more harm than good." },
    { label: "D", text: "Interpretations of the Constitution can change, which in turn affect decisions made by lawmakers." },
  ],
  q26: [
    { label: "A", text: "People with incomes under $40,000 are twice as likely to be called as are those with higher incomes." },
    { label: "B", text: "A greater percentage of adults from households with incomes of more than $40,000 have served on juries than the percentage of those from households with lower incomes." },
    { label: "C", text: "People with lower incomes are more likely to want to serve on juries." },
    { label: "D", text: "Most jurors have incomes between $30,000 and $35,000." },
  ],
  q27: [
    { label: "A", text: "the invention of a safe radioactive-waste disposal method" },
    { label: "B", text: "the discovery of a cleaner method of burning coal" },
    { label: "C", text: "a decrease in taxes on fossil fuels" },
    { label: "D", text: "increased oil exploration in Alaska" },
  ],
  q28: [
    { label: "A", text: "smoke" },
    { label: "B", text: "smog" },
    { label: "C", text: "erosion" },
    { label: "D", text: "turbines" },
  ],
  q29: [
    { label: "A", text: "a desert community with little or no fossil fuel resources" },
    { label: "B", text: "a town adjacent to a large river" },
    { label: "C", text: "a community with large oil reserves" },
    { label: "D", text: "a community in coal-rich West Virginia" },
  ],
  q30: [
    { label: "A", text: "Theodore Roosevelt in the Spanish-American War" },
    { label: "B", text: "Douglas MacArthur in World War II" },
    { label: "C", text: "Count Frontenac in King William’s War" },
    { label: "D", text: "Norman Schwarzkopf in the Persian Gulf War" },
  ],
  q31: [
    { label: "A", text: "Economic interests should outweigh sentimental interests." },
    { label: "B", text: "It is acceptable to destroy natural beauty in some cases." },
    { label: "C", text: "Things that humans value should be used for human benefit." },
    { label: "D", text: "Some things have value that cannot be measured in monetary terms." },
  ],
  q32: [
    { label: "A", text: "D, A, C, B" },
    { label: "B", text: "C, B, D, A" },
    { label: "C", text: "A, C, B, D" },
    { label: "D", text: "D, B, A, C" },
  ],
  q33: [
    { label: "A", text: "Orlando, Florida" },
    { label: "B", text: "New Orleans, Louisiana" },
    { label: "C", text: "Chicago, Illinois" },
    { label: "D", text: "Virginia Beach, Virginia" },
  ],
  q35: [
    { label: "A", text: "was forced to leave office after being impeached by the Congress." },
    { label: "B", text: "resigned before completing his term of office." },
    { label: "C", text: "appointed Vice President Ford as interim president." },
    { label: "D", text: "continued on as full-time president, despite pressure from Congress." },
  ],
} as const;

type AnswerRecord = {
  number: number;
  groupId: string;
  section: string;
  topic: string;
  reference: string;
  prompt: string;
  choices: readonly { label: string; text: string }[];
  correctLabel: string | null;
  answerLine: string;
  explanation: string;
  sourcePage: number;
};

const groupById = new Map<string, (typeof supplementalPrincetonSocialStudiesTest2Groups)[number]>(supplementalPrincetonSocialStudiesTest2Groups.map((group) => [group.id, group]));
const promptFor = (groupId: string, number: number) => groupById.get(groupId)?.questions.find((question) => question.number === number)?.text || "";
const makeQuestion = (number: number, groupId: string, choicesFor: readonly { label: string; text: string }[], correctLabel: string | null, answerLine: string, explanation: string, sourcePage: number): AnswerRecord => {
  const group = groupById.get(groupId);
  if (!group) throw new Error(`Unknown Princeton Social Studies Test 2 group: ${groupId}`);
  return { number, groupId, section: group.section, topic: group.topic, reference: "Princeton Social Studies Test 2", prompt: promptFor(groupId, number), choices: choicesFor, correctLabel, answerLine, explanation, sourcePage };
};

export const supplementalPrincetonSocialStudiesTest2Questions: readonly AnswerRecord[] = [
  makeQuestion(1, "princeton-ss-practice-1-2", choices.q1, "D", "D. They were wary of giving the government too much power over individual rights.", "The passage says the amendments and the 14th Amendment were intended to protect individual rights from government encroachment.", 2),
  makeQuestion(2, "princeton-ss-practice-1-2", choices.q2, "B", "B. legislation requiring citizens to pay taxes regardless of their beliefs.", "A law requiring all citizens to pay taxes regardless of their beliefs does not deny equal protection or due process under the 14th Amendment. The other choices do.", 3),
  makeQuestion(3, "princeton-ss-practice-3", choices.q3, "D", "D. a lack of respect by some members of the press for women’s abilities", "The passage emphasizes that members of the press called Earhart foolish, publicity-seeking, or better suited to domestic pursuits.", 3),
  makeQuestion(4, "princeton-ss-practice-4", [], null, "Yes, No, Yes, No, Yes", "Statements (a), (c), and (e) are supported by the graph. Statements (b) and (d) refer to all employees rather than union members, which is what the graph measures. The combined union membership is lower in 2009 than in 2000.", 4),
  makeQuestion(5, "princeton-ss-practice-5", choices.q5, "D", "D. less growth in precision production than in professional specialties.", "Precision production grew by less than professional specialties. Agriculture declined, services grew more than administrative support, and administrative support did not exceed the combined growth of services and technicians.", 5),
  makeQuestion(6, "princeton-ss-practice-6", choices.q6, "C", "C. Sub-Saharan Africa is in desperate need of foreign aid in order to sustain its economy.", "Choices A, B, and D can be checked against the graph. Choice C expresses a judgment about what should be done, so it is an opinion.", 6),
  makeQuestion(7, "princeton-ss-practice-7", choices.q7, "A", "A. Manifest Destiny.", "The belief that divine providence ordained U.S. expansion across the continent is called Manifest Destiny.", 7),
  makeQuestion(8, "princeton-ss-practice-8-9", choices.q8, "C", "C. American males", "The graph shows that females live longer than males in each country and that American males have the shortest life expectancy among the listed groups.", 8),
  makeQuestion(9, "princeton-ss-practice-8-9", choices.q9, "C", "C. Japan provides free or low-cost health care for all Japanese citizens.", "The graph shows Japan with slightly higher life expectancy, and free or low-cost health care offers a plausible explanation. The other choices do not account for the comparison.", 8),
  makeQuestion(10, "princeton-ss-practice-10-12", choices.q10, "D", "D. Efforts have been made to ensure that America is receptive to immigrants.", "The article describes legislation and improved public awareness intended to promote equal treatment and help the United States live up to its melting-pot image.", 9),
  makeQuestion(11, "princeton-ss-practice-10-12", choices.q11, "A", "A. the United States offers political stability and economic opportunity.", "The passage says immigrants come in search of new opportunities, social mobility, and freedom from political unrest and oppression.", 10),
  makeQuestion(12, "princeton-ss-practice-10-12", choices.q12, "D", "D. Immigrants make more money after coming to America.", "The passage supports the other statements but does not directly say that immigrants make more money after arriving.", 10),
  makeQuestion(13, "princeton-ss-practice-13", choices.q13, "D", "D. a constitutional amendment giving new immigrants voting rights", "The advertisement is hostile to immigrants and foreigners holding office, so its writer would oppose extending voting rights to new immigrants.", 11),
  makeQuestion(14, "princeton-ss-practice-14", choices.q14, "C", "C. Most Western states had guaranteed full suffrage to women before 1920.", "The map shows that many Western states granted women full suffrage before the 19th Amendment was ratified. The other choices are too broad or unsupported.", 12),
  makeQuestion(15, "princeton-ss-practice-15", choices.q15, "B", "B. a united defense", "The Preamble mentions providing for the common defense, while the Declaration mentions liberty, equality, and happiness but not a united defense.", 13),
  makeQuestion(16, "princeton-ss-practice-16", choices.q16, "D", "D. oil refining", "The graph shows oil refining as the least crisis-prone category among the choices.", 14),
  makeQuestion(17, "princeton-ss-practice-17-18", choices.q17, "C", "C. Europe and Asia", "The population-density map shows Europe and Asia as the most densely populated continents.", 15),
  makeQuestion(18, "princeton-ss-practice-17-18", choices.q18, "A", "A. climate and geography", "Climate and geography determine whether environments such as deserts, arctic regions, or mountainous areas can support dense populations.", 15),
  makeQuestion(19, "princeton-ss-practice-19", choices.q19, "B", "B. Inspired by the principle of Manifest Destiny, President James K. Polk, a Democrat elected in 1845, sought to secure American control of the Southwest after the Mexican-American War.", "The sources identify Democrats as supporters of expansion and connect Manifest Destiny with westward expansion. Polk’s presidency and the map are consistent with choice B.", 16),
  makeQuestion(20, "princeton-ss-practice-20", choices.q20, "A", "A. a constitutional republic", "Lincoln’s quote describes majority rule constrained by constitutional checks and limitations, which is characteristic of a constitutional republic.", 18),
  makeQuestion(21, "princeton-ss-practice-21", choices.q21, "A", "A. New technology will cause companies to decrease the size of their workforce in order to cut costs.", "Choice A presents a negative consequence of technology that contradicts the passage’s conclusion that workers and employers benefit.", 18),
  makeQuestion(22, "princeton-ss-practice-22", choices.q22, "B", "B. Southeastern states generally have a lower median income than Northeastern states.", "The income map supports the general comparison between the Southeast and Northeast. The other choices are contradicted or too broad for the data shown.", 19),
  makeQuestion(23, "princeton-ss-practice-23", choices.q23, "D", "D. Brown v. Board of Education found that ‘separate but equal’ facilities were a violation of the 14th Amendment.", "Brown held that separate educational facilities are inherently unequal, directly applying the 14th Amendment’s equal-protection principle against segregation in public education.", 20),
  makeQuestion(24, "princeton-ss-practice-24", choices.q24, "D", "D. caused the expansion of the cotton industry in the American South.", "By making cotton processing much more efficient, the cotton gin caused the cotton industry to expand in the South.", 22),
  makeQuestion(25, "princeton-ss-practice-25", choices.q25, "D", "D. Interpretations of the Constitution can change, which in turn affect decisions made by lawmakers.", "The example of Congress approving a peacetime draft after a changed interpretation shows that constitutional interpretations can change and affect policy decisions.", 22),
  makeQuestion(26, "princeton-ss-practice-26", choices.q26, "B", "B. A greater percentage of adults from households with incomes of more than $40,000 have served on juries than the percentage of those from households with lower incomes.", "The survey shows that the percentage who served is higher among adults from households earning more than $40,000 than among adults from lower-income households.", 24),
  makeQuestion(27, "princeton-ss-practice-27-29", choices.q27, "A", "A. the invention of a safe radioactive-waste disposal method", "The major problem identified for nuclear power is the danger of its by-products. A safe disposal method would make greater use more likely.", 25),
  makeQuestion(28, "princeton-ss-practice-27-29", choices.q28, "D", "D. turbines", "All three methods use energy to turn turbines and produce electricity. Smoke, smog, and erosion are not common to all three.", 26),
  makeQuestion(29, "princeton-ss-practice-27-29", choices.q29, "B", "B. a town adjacent to a large river", "Hydroelectric power requires the force of a river, so a town near a large river is the most likely choice.", 26),
  makeQuestion(30, "princeton-ss-practice-30", choices.q30, "A", "A. Theodore Roosevelt in the Spanish-American War", "The Big Stick in the Caribbean Sea cartoon refers to Theodore Roosevelt’s big-stick foreign policy in the Spanish-American War era.", 26),
  makeQuestion(31, "princeton-ss-practice-31", choices.q31, "D", "D. Some things have value that cannot be measured in monetary terms.", "John Muir’s conservation work shows that wilderness and natural beauty have value beyond their economic usefulness.", 27),
  makeQuestion(32, "princeton-ss-practice-32", choices.q32, "D", "D. D, B, A, C", "Reading the longitudes on the globe from west to east gives the order D, B, A, C.", 28),
  makeQuestion(33, "princeton-ss-practice-33", choices.q33, "C", "C. Chicago, Illinois", "Chicago is not located near the Atlantic Ocean or the Gulf of Mexico and is therefore the least threatened by hurricanes among the choices.", 28),
  makeQuestion(34, "princeton-ss-practice-34", [], null, "No, No, Yes, No", "Only statement (c) is supported: the proclamation specifically names people resisting militia drafts as subject to martial law and military punishment. The other statements are not supported by the quote.", 29),
  makeQuestion(35, "princeton-ss-practice-35", choices.q35, "B", "B. resigned before completing his term of office.", "Nixon explicitly said he would resign the presidency effective the next day. The quote does not say that he was impeached or appointed Ford as interim president.", 30),
];
