export const supplementalKaplanSocialStudiesPretestGroups = [
  {
    id: "kaplan-pretest-ss-practice-1",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 1,
    questionEnd: 1,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Question 1",
    contextType: "passage",
    marker: "Question 1 refers to the following passage.",
    context: "The passage explains that the Fifteenth Amendment extended voting rights to African American men, but Southern states used poll taxes, literacy tests, and grandfather clauses to prevent many African Americans from voting. It describes the civil rights movement and the Voting Rights Act of 1965, which provided federal oversight and outlawed discriminatory barriers.",
    sourcePages: [1, 1],
    visualPage: null,
    questions: [{ number: 1, text: "Which of the following describes the author’s main idea?" }],
  },
  {
    id: "kaplan-pretest-ss-practice-2",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 2,
    questionEnd: 2,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Question 2",
    contextType: "passage",
    marker: "Question 2 refers to the following passage.",
    context: "Alexander Hamilton proposed a national bank to help pay the nation’s debt and stabilize its currency. Supporters of a strict construction of the Constitution argued that the federal government could exercise only specifically listed powers. Hamilton defended the bank using a loose construction and the Necessary and Proper Clause.",
    sourcePages: [2, 2],
    visualPage: null,
    questions: [{ number: 2, text: "What is meant by the term “construction” in the passage?" }],
  },
  {
    id: "kaplan-pretest-ss-practice-3-4",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 3,
    questionEnd: 4,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Questions 3–4",
    contextType: "passage",
    marker: "Questions 3 and 4 refer to the following passage.",
    context: "The Food and Drug Administration proposed requiring calorie information to be posted at food retailers. The passage argues that the rules would create a financial burden, especially for smaller restaurants, grocery stores, and convenience stores, and describes proposed exemptions for some smaller businesses and remote-order restaurants.",
    sourcePages: [2, 3],
    visualPage: null,
    questions: [
      { number: 3, text: "What is the author’s point of view regarding the FDA’s new food regulations?" },
      { number: 4, text: "Which one of the following words points to the author’s viewpoint regarding the FDA’s strict new regulations?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-practice-5-6",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 5,
    questionEnd: 6,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Questions 5–6",
    contextType: "passage",
    marker: "Questions 5 and 6 refer to the following paragraph.",
    context: "The paragraph argues that drilling for oil in Alaska’s Arctic National Wildlife Refuge should not be rejected because most species that once lived on Earth became extinct naturally. It uses the porcupine caribou as the commonly cited environmental objection but does not address other possible reasons against drilling.",
    sourcePages: [3, 4],
    visualPage: null,
    questions: [
      { number: 5, text: "Which of the following statements is a correct evaluation of the argument?" },
      { number: 6, text: "Which of the following considerations, if true, best illustrates why the author’s evidence is inadequate?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-practice-7-8",
    section: "Social Studies",
    topic: "World History",
    questionStart: 7,
    questionEnd: 8,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Questions 7–8",
    contextType: "map",
    marker: "Questions 7 and 8 are based on the following information and map.",
    context: "After World War II, Germany was divided into democratic West Germany and communist East Germany. West Germany joined NATO and rearmed in 1955; in response, the Soviet Union and communist Eastern European countries formed the Warsaw Pact. The pact placed smaller communist countries’ military forces under Soviet command.",
    sourcePages: [4, 6],
    visualPage: 5005,
    questions: [
      { number: 7, text: "Some historians believe that, in forming the Warsaw Pact, the Soviet Union wanted to create a buffer between itself and NATO countries. How does the map support that view?" },
      { number: 8, text: "The map could be used to dispute which one of the following claims?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-practice-9",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 9,
    questionEnd: 9,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Question 9",
    contextType: "table",
    marker: "Question 9 refers to the following table and map.",
    context: "Average yearly rainfall in New England: Connecticut 47 inches, Maine 41 inches, Massachusetts 45 inches, New Hampshire 42 inches, Rhode Island 44 inches, and Vermont 39 inches.",
    sourcePages: [6, 7],
    visualPage: 5006,
    questions: [{ number: 9, text: "What is the average (arithmetic mean) yearly rainfall, in inches, of the three northernmost states in New England?" }],
  },
  {
    id: "kaplan-pretest-ss-practice-10",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 10,
    questionEnd: 10,
    rangeLabel: "Kaplan Social Studies Pretest · Practice Question 10",
    contextType: "graph",
    marker: "Question 10 refers to the following graph.",
    context: "The line graph shows the percentage of eligible people who voted in presidential elections from 1996 through 2012, separated by race and Hispanic origin.",
    sourcePages: [7, 8],
    visualPage: 5008,
    questions: [{ number: 10, text: "Over the period illustrated by the line graph, the rate at which eligible black voters participated in presidential elections" }],
  },
  {
    id: "kaplan-pretest-ss-content-1-2",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 1,
    questionEnd: 2,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 1–2",
    contextType: "map",
    marker: "Questions 1 and 2 refer to the following map.",
    context: "The Colonial Triangular Trade map shows routes from the West Indies to the British colonies, from the British colonies to Africa, and from Africa to the West Indies. It labels sugar and molasses, rum, and gold and enslaved people along the routes.",
    sourcePages: [9, 10],
    visualPage: 5009,
    questions: [
      { number: 1, text: "Based on this map, what were the three sides of the triangle in the triangular trade?" },
      { number: 2, text: "Which statement is a conclusion based on the map rather than a supporting detail from the map?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-3",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 3,
    questionEnd: 3,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 3",
    contextType: "passage",
    marker: "Question 3 refers to the following information.",
    context: "Federal Reserve Banks control monetary policy and maintain financial stability. Commercial banks accept deposits, make loans, and serve corporations and businesses. Retail banks serve consumers, community development banks support low- to moderate-income areas, and credit unions serve their members at lower interest rates.",
    sourcePages: [10, 11],
    visualPage: null,
    questions: [{ number: 3, text: "At which type of financial institution would the ABC Printing Company be most likely to take out a loan to finance the purchase of a new printing press?" }],
  },
  {
    id: "kaplan-pretest-ss-content-4-5",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 4,
    questionEnd: 5,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 4–5",
    contextType: "passage",
    marker: "Questions 4 and 5 refer to the following passage.",
    context: "A passage describes corruption in Somerville from the 1960s through the 1980s and argues that its strong-mayor system caused the corruption. It concludes that the current mayor should be viewed with strong suspicion because the same system remains in place.",
    sourcePages: [11, 12],
    visualPage: null,
    questions: [
      { number: 4, text: "Which of the following words or phrases is based on the author’s opinion, NOT fact?" },
      { number: 5, text: "Is the author’s conclusion properly supported by evidence?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-6",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 6,
    questionEnd: 6,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 6",
    contextType: "passage",
    marker: "Question 6 is based on the following statement.",
    context: "The item asks which action represents participation in the U.S. system of government.",
    sourcePages: [12, 12],
    visualPage: null,
    questions: [{ number: 6, text: "Most Americans believe it is their duty as citizens to take part in our system of government. Which of the following actions represents participation in government?" }],
  },
  {
    id: "kaplan-pretest-ss-content-7",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 7,
    questionEnd: 7,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 7",
    contextType: "passage",
    marker: "Question 7 is based on the following paragraph.",
    context: "The paragraph describes repeated shifts between military and civilian rule in several Latin American countries. Civilian governments attempt reforms that lead to unrest, after which military governments impose strict controls.",
    sourcePages: [12, 12],
    visualPage: null,
    questions: [{ number: 7, text: "Which of the following is highly valued by those who favor military rule?" }],
  },
  {
    id: "kaplan-pretest-ss-content-8-9",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 8,
    questionEnd: 9,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 8–9",
    contextType: "table",
    marker: "Questions 8 and 9 refer to the following chart.",
    context: "Presidential Powers in Several Nations compares the powers of the presidents of the United States, South Africa, France, and Mexico, including control of armed forces, approval of legislation, appointments, appointment of a prime minister, and dissolution of the legislature.",
    sourcePages: [12, 13],
    visualPage: 5013,
    questions: [
      { number: 8, text: "Which of the following is a difference between the powers of the U.S. and French presidents?" },
      { number: 9, text: "Which of the following statements is a conclusion based on the chart, rather than a detail?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-10",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 10,
    questionEnd: 10,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 10",
    contextType: "passage",
    marker: "Question 10 refers to the following paragraph.",
    context: "The passage discusses Jim Crow laws and Plessy v. Ferguson, an 1896 Supreme Court case involving segregated railroad cars. The Court upheld separate facilities, while a dissenting justice argued that the decision was inconsistent with personal liberty.",
    sourcePages: [13, 14],
    visualPage: null,
    questions: [{ number: 10, text: "Which of the following statements is an opinion rather than a fact?" }],
  },
  {
    id: "kaplan-pretest-ss-content-11-12",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 11,
    questionEnd: 12,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 11–12",
    contextType: "graph",
    marker: "Questions 11 and 12 refer to the following paragraph and graph.",
    context: "The U.S. government borrows by selling bonds and pays back principal and interest over time. The graph shows per capita national debt every five years from 1990 through 2010, rising from about $12,980 to $42,648.",
    sourcePages: [14, 15],
    visualPage: 5015,
    questions: [
      { number: 11, text: "Which of the following conclusions is supported by the data in the paragraph and the graph?" },
      { number: 12, text: "Which action would enable the U.S. government to reduce its debt?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-13",
    section: "Social Studies",
    topic: "World History",
    questionStart: 13,
    questionEnd: 13,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 13",
    contextType: "passage",
    marker: "Question 13 refers to the following paragraph.",
    context: "New geological and archaeological evidence suggests that Mayan deforestation in the Yucatan peninsula may have contributed as much as 60 percent of the dry weather associated with the ninth-century BCE collapse of the Mayan empire.",
    sourcePages: [16, 16],
    visualPage: null,
    questions: [{ number: 13, text: "According to the theory presented in the paragraph, what was the effect of Mayan deforestation of the Yucatan peninsula?" }],
  },
  {
    id: "kaplan-pretest-ss-content-14",
    section: "Social Studies",
    topic: "World History",
    questionStart: 14,
    questionEnd: 14,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 14",
    contextType: "map",
    marker: "Question 14 refers to the following map.",
    context: "The map shows Great Britain during the Industrial Revolution in 1830, including cities with more than 300,000 people, iron ore deposits, and coalfields.",
    sourcePages: [16, 17],
    visualPage: 5016,
    questions: [{ number: 14, text: "Which of the following is a conclusion based on the map, rather than a supporting detail from the map?" }],
  },
  {
    id: "kaplan-pretest-ss-content-15",
    section: "Social Studies",
    topic: "World History",
    questionStart: 15,
    questionEnd: 15,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 15",
    contextType: "passage",
    marker: "Question 15 is based on the following definition.",
    context: "When a nation follows a policy of appeasement, it makes concessions to an aggressor in order to preserve peace.",
    sourcePages: [17, 18],
    visualPage: null,
    questions: [{ number: 15, text: "Which of the following is an example of appeasement?" }],
  },
  {
    id: "kaplan-pretest-ss-content-16-18",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 16,
    questionEnd: 18,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 16–18",
    contextType: "figure",
    marker: "Questions 16 through 18 refer to the following poster.",
    context: "A World War I government poster urges Americans to buy a United States Government Bond of the Loan of 1917. Its message contrasts Americans’ willingness to risk their sons’ lives with their reluctance to finance the war effort.",
    sourcePages: [18, 19],
    visualPage: 5018,
    questions: [
      { number: 16, text: "Which of the following statements summarizes the assumption behind the poster?" },
      { number: 17, text: "During which war was this poster part of a government advertising campaign?" },
      { number: 18, text: "If the government were running a similar advertising campaign today, which medium would probably reach the most people?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-19",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 19,
    questionEnd: 19,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 19",
    contextType: "table",
    marker: "Question 19 refers to the following table.",
    context: "The Five Most Populous American Colonies in 1750: Virginia 231,000; Massachusetts 188,000; Maryland 141,000; Pennsylvania 119,700; Connecticut 111,300.",
    sourcePages: [19, 20],
    visualPage: 5019,
    questions: [{ number: 19, text: "Which of the following statements is supported by the data in the chart?" }],
  },
  {
    id: "kaplan-pretest-ss-content-20-22",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 20,
    questionEnd: 22,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 20–22",
    contextType: "diagram",
    marker: "Questions 20 through 22 refer to the following paragraph and flowchart.",
    context: "The federal Civil Service system is designed to appoint people based on skills and abilities rather than political affiliation. The flowchart shows the steps from finding a job opening and completing an application through taking an exam, entering a register, interviewing, and receiving a GS rating if hired.",
    sourcePages: [20, 21],
    visualPage: 5020,
    questions: [
      { number: 20, text: "Which of the following is the best title for the flowchart?" },
      { number: 21, text: "What does a civil servant’s GS rating probably affect most?" },
      { number: 22, text: "On which of the following values does the structure of the Civil Service system primarily rest?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-23-24",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 23,
    questionEnd: 24,
    rangeLabel: "Kaplan Social Studies Pretest · Content Questions 23–24",
    contextType: "graph",
    marker: "Questions 23 and 24 refer to the following graphs.",
    context: "The graphs show interest rates for conventional mortgages and total U.S. mortgage debt outstanding over the same period, allowing the learner to compare interest-rate and debt trends.",
    sourcePages: [21, 22],
    visualPage: 5022,
    questions: [
      { number: 23, text: "In 2005, what were the approximate interest rate and approximate total mortgage debt outstanding for a conventional mortgage?" },
      { number: 24, text: "Based on the graphs, how do mortgage interest rates and total mortgage debt outstanding compare?" },
    ],
  },
  {
    id: "kaplan-pretest-ss-content-25",
    section: "Social Studies",
    topic: "World History",
    questionStart: 25,
    questionEnd: 25,
    rangeLabel: "Kaplan Social Studies Pretest · Content Question 25",
    contextType: "passage",
    marker: "Question 25 refers to the following paragraph.",
    context: "A culture hearth is a center from which ideas, values, customs, fashions, and practices spread. The paragraph gives the Nile River region as an ancient example and asks for a modern culture hearth with worldwide influence.",
    sourcePages: [23, 23],
    visualPage: null,
    questions: [{ number: 25, text: "Which of the following is an example of a modern culture hearth with worldwide influence?" }],
  },
] as const;

const choices = {
  p1: [
    { label: "A", text: "The Voting Rights Act of 1965 ended discrimination in all areas of American society." },
    { label: "B", text: "The main effect of the Voting Rights Act of 1965 was to empower individual states to end discriminatory measures against African American voting." },
    { label: "C", text: "The Voting Rights Act of 1965 gave the federal government oversight of state elections to end barriers against African American voting." },
    { label: "D", text: "The Fifteenth Amendment did not end racism in Southern states." },
  ],
  p2: [
    { label: "A", text: "building" },
    { label: "B", text: "creation" },
    { label: "C", text: "interpretation" },
    { label: "D", text: "structure" },
  ],
  p3: [
    { label: "A", text: "The FDA’s new regulations would place a financial hardship on small food retailers." },
    { label: "B", text: "The FDA’s new regulations would help consumers choose foods of a higher nutritional value." },
    { label: "C", text: "The FDA’s new regulations would have a more severe financial impact on chain restaurants than on smaller food retailers." },
    { label: "D", text: "The FDA’s new regulations would give food retailers more diverse options for displaying caloric information." },
  ],
  p4: [
    { label: "A", text: "aware" },
    { label: "B", text: "strict" },
    { label: "C", text: "devastating" },
    { label: "D", text: "remotely" },
  ],
  p5: [
    { label: "A", text: "The argument is valid, because it relies on scientific evidence that has been shown to be true." },
    { label: "B", text: "The argument is valid, because extracting oil would bolster the national economy." },
    { label: "C", text: "The argument is invalid, because it confuses correlation with causation." },
    { label: "D", text: "The argument is invalid, because it attempts to refute one reason against doing something while ignoring other possible reasons." },
  ],
  p6: [
    { label: "A", text: "Some people depend on the porcupine caribou for food." },
    { label: "B", text: "People who call themselves ‘scientists’ often make claims that are very persuasive." },
    { label: "C", text: "There is not enough oil in the ANWR to have a measurable impact on global oil prices." },
    { label: "D", text: "Extracting oil from the ANWR would reduce the foreign trade deficit." },
  ],
  p7: [
    { label: "A", text: "The map indicates that many of the World War II Allies joined the Warsaw Pact, but not until the 1960s." },
    { label: "B", text: "The map shows that most of the Warsaw Pact countries lay between the Soviet Union and Western countries, including France, West Germany, and Great Britain." },
    { label: "C", text: "The map shows that the Warsaw Pact involved the building of a wall between the Soviet Union and Western Europe." },
    { label: "D", text: "The map indicates that the Soviet Union was made up of smaller republics on its western border." },
  ],
  p8: [
    { label: "A", text: "In forming the Warsaw Pact, the Soviet Union greatly increased its access to oceanic coastline." },
    { label: "B", text: "In forming the Warsaw Pact, the Soviet Union wished to increase its trade with Africa." },
    { label: "C", text: "The Warsaw Pact benefitted Bulgaria and Romania no less than the Soviet Union." },
    { label: "D", text: "The Warsaw Pact initially included Albania." },
  ],
  p9: [
    { label: "A", text: "40" },
    { label: "B", text: "41" },
    { label: "C", text: "42" },
    { label: "D", text: "43" },
  ],
  p10: [
    { label: "A", text: "fluctuated up and down, but ended higher than it began" },
    { label: "B", text: "steadily increased, surpassing that of white voters in the 2012 elections" },
    { label: "C", text: "increased sharply in the middle of the time period shown on the graph before dropping back closer to its original level" },
    { label: "D", text: "was consistently lower than the rates of most other races and ethnic groups" },
  ],
  c1: [
    { label: "A", text: "Europe to the West Indies; the West Indies to Africa; Africa to the British colonies" },
    { label: "B", text: "the West Indies to the British colonies; the British colonies to Africa; Africa to the West Indies" },
    { label: "C", text: "the West Indies to England; England to the British colonies; the British colonies to Africa" },
    { label: "D", text: "South America to Africa; Africa to the West Indies; the West Indies to the British colonies" },
  ],
  c2: [
    { label: "A", text: "Cargo ships never had to sail empty on any leg of a profitable triangular journey." },
    { label: "B", text: "The journey of Africans from Africa to the Americas was called the Middle Passage." },
    { label: "C", text: "Slaves sometimes were transported on cargo ships from the West Indies to the British colonies." },
    { label: "D", text: "Rum was shipped from one of the ports on the east coast of North America." },
  ],
  c3: [
    { label: "A", text: "Federal Reserve Bank" },
    { label: "B", text: "commercial bank" },
    { label: "C", text: "retail bank" },
    { label: "D", text: "community development bank" },
  ],
  c4: [
    { label: "A", text: "long history" },
    { label: "B", text: "tainted system" },
    { label: "C", text: "bribery" },
    { label: "D", text: "mayors, councilors, and tax assessors" },
  ],
  c5: [
    { label: "A", text: "Yes, because the corruption in Somerville spreads beyond the office of the mayor." },
    { label: "B", text: "Yes, because 20 years of corruption can accurately be called a ‘long history.’" },
    { label: "C", text: "No, because there is no mention of criminal investigation or charges." },
    { label: "D", text: "No, because no indication is given that the current mayor will behave as past mayors did." },
  ],
  c6: [
    { label: "A", text: "pursuing higher education" },
    { label: "B", text: "displaying the American flag" },
    { label: "C", text: "volunteering at a hospital" },
    { label: "D", text: "serving on a jury" },
  ],
  c7: [
    { label: "A", text: "social welfare" },
    { label: "B", text: "freedom" },
    { label: "C", text: "democracy" },
    { label: "D", text: "law and order" },
  ],
  c8: [
    { label: "A", text: "The U.S. president controls the armed forces, and the French president does not." },
    { label: "B", text: "The U.S. president approves legislation, and the French president does not." },
    { label: "C", text: "The French president has the power to dissolve the legislature, while the U.S. president does not." },
    { label: "D", text: "The French president has the power to appoint judges, while the U.S. president does not." },
  ],
  c9: [
    { label: "A", text: "The president of South Africa cannot dissolve the legislature." },
    { label: "B", text: "Of all the presidents shown, the French president has the greatest variety of powers." },
    { label: "C", text: "The president of Mexico has the power to appoint judges." },
    { label: "D", text: "The U.S. president has the power to approve legislation." },
  ],
  c10: [
    { label: "A", text: "In the late 1800s, many southern states passed Jim Crow laws to keep whites and blacks separate in public places." },
    { label: "B", text: "In Louisiana, a law required separate railroad cars for white and black passengers." },
    { label: "C", text: "Plessy v. Ferguson was an 1896 Supreme Court case that challenged the Louisiana law related to segregated railroad cars." },
    { label: "D", text: "The U.S. Supreme Court ruling in Plessy v. Ferguson was wrong because it infringed on freedoms guaranteed in the Constitution." },
  ],
  c11: [
    { label: "A", text: "The nation’s debt increased at a faster rate than did the U.S. population during the period shown on the graph." },
    { label: "B", text: "Every person in the United States owed an average of $20,000 to the government in the year 2000." },
    { label: "C", text: "In 1990, the U.S. government owed every American about $13,000." },
    { label: "D", text: "The U.S. government sold about $5.7 trillion worth of bonds in 2000." },
  ],
  c12: [
    { label: "A", text: "postpone payment of that debt" },
    { label: "B", text: "pay interest to foreign investors" },
    { label: "C", text: "pay interest to U.S. investors" },
    { label: "D", text: "raise taxes and cut spending" },
  ],
  c13: [
    { label: "A", text: "The Mayans needed more land to grow crops." },
    { label: "B", text: "Scientists discovered new evidence in the geological record." },
    { label: "C", text: "A drought was significantly worsened due to lack of native vegetation." },
    { label: "D", text: "Baking bricks required an enormous amount of wood." },
  ],
  c14: [
    { label: "A", text: "The Industrial Revolution took place in Great Britain around the year 1830." },
    { label: "B", text: "More than 300,000 people lived in Sheffield around 1830." },
    { label: "C", text: "Many cities had large populations because nearby coal and iron ore deposits meant jobs." },
    { label: "D", text: "There was a large area with coal deposits in southern Wales around 1830." },
  ],
  c15: [
    { label: "A", text: "Italy’s support of Spanish Nationalists in the Spanish Civil War in the late 1930s" },
    { label: "B", text: "Great Britain’s acceptance of Germany’s takeover of Austria and Czechoslovakia in the late 1930s" },
    { label: "C", text: "Germany’s 1939 invasion of Poland, which started World War II" },
    { label: "D", text: "Japan’s alliance with Germany and Italy in 1940, which created the Rome-Berlin-Tokyo Axis" },
  ],
  c16: [
    { label: "A", text: "People will give to the war effort because they are doing well economically." },
    { label: "B", text: "Financing the war requires selling bonds and raising taxes." },
    { label: "C", text: "During wartime, people have little money to spend on their sons." },
    { label: "D", text: "People value the lives of their children more than they value money." },
  ],
  c17: [
    { label: "A", text: "the Civil War" },
    { label: "B", text: "World War I" },
    { label: "C", text: "World War II" },
    { label: "D", text: "the Vietnam War" },
  ],
  c18: [
    { label: "A", text: "posters" },
    { label: "B", text: "leaflets and brochures" },
    { label: "C", text: "print ads in financial newspapers" },
    { label: "D", text: "ads on social media" },
  ],
  c19: [
    { label: "A", text: "The population of all of the American colonies was less than 700,000." },
    { label: "B", text: "Virginia had more than twice as many people as Maryland." },
    { label: "C", text: "Most of the population of Massachusetts was of English origin." },
    { label: "D", text: "The population of the colony of New York was smaller than that of Connecticut." },
  ],
  c20: [
    { label: "A", text: "A History of the Civil Service" },
    { label: "B", text: "The Qualifications of Civil Service Workers" },
    { label: "C", text: "Applying for Civil Service Jobs" },
    { label: "D", text: "Interviewing for a Civil Service Job" },
  ],
  c21: [
    { label: "A", text: "salary" },
    { label: "B", text: "length of service" },
    { label: "C", text: "job security" },
    { label: "D", text: "education level" },
  ],
  c22: [
    { label: "A", text: "patriotism" },
    { label: "B", text: "equal opportunity" },
    { label: "C", text: "freedom of speech" },
    { label: "D", text: "respect for seniority" },
  ],
  c23: [
    { label: "A", text: "8 percent and $13,000 billion" },
    { label: "B", text: "4 percent and $11,000 billion" },
    { label: "C", text: "6 percent and $12,000 billion" },
    { label: "D", text: "6 percent and $9,000 billion" },
  ],
  c24: [
    { label: "A", text: "Interest rates rise in direct proportion to decreases in total mortgage debt outstanding." },
    { label: "B", text: "The higher the interest rate, the lower the total mortgage debt outstanding." },
    { label: "C", text: "The lower the interest rate, the higher the total mortgage debt outstanding." },
    { label: "D", text: "As interest rates rise and then fall, the total mortgage debt will move similarly but not at the same rate." },
  ],
  c25: [
    { label: "A", text: "Pyongyang, capital of North Korea, which has a 95 percent literacy rate" },
    { label: "B", text: "Ottawa, capital of Canada, with a population of about one million" },
    { label: "C", text: "New Zealand, which exports wool and textiles" },
    { label: "D", text: "Hollywood, California, which produces movies and television shows, enjoyed around the world" },
  ],
} as const;

type AnswerRecord = {
  number: number;
  groupId: string;
  section: string;
  topic: string;
  reference: string;
  prompt: string;
  choices: readonly { label: string; text: string }[];
  correctLabel: string | null;
  answerLine: string;
  explanation: string;
  sourcePage: number;
};

const groupById = new Map<string, (typeof supplementalKaplanSocialStudiesPretestGroups)[number]>(supplementalKaplanSocialStudiesPretestGroups.map((group) => [group.id, group]));
const promptFor = (groupId: string, number: number) => groupById.get(groupId)?.questions.find((question) => question.number === number)?.text || "";
const makeQuestion = (number: number, groupId: string, choicesFor: readonly { label: string; text: string }[], correctLabel: string | null, answerLine: string, explanation: string, sourcePage: number): AnswerRecord => {
  const group = groupById.get(groupId);
  if (!group) throw new Error(`Unknown Kaplan Social Studies pretest group: ${groupId}`);
  return { number, groupId, section: group.section, topic: group.topic, reference: "Kaplan Social Studies Pretest", prompt: promptFor(groupId, number), choices: choicesFor, correctLabel, answerLine, explanation, sourcePage };
};

export const supplementalKaplanSocialStudiesPretestQuestions: readonly AnswerRecord[] = [
  makeQuestion(1, "kaplan-pretest-ss-practice-1", choices.p1, "C", "C. The Voting Rights Act of 1965 gave the federal government oversight of state elections to end barriers against African American voting.", "The passage describes the historical events leading to the Voting Rights Act and explains how the law ended voting barriers enacted by some states after the Fifteenth Amendment.", 1),
  makeQuestion(2, "kaplan-pretest-ss-practice-2", choices.p2, "C", "C. interpretation", "The terms strict construction and loose construction refer to different ways of interpreting the range of powers the Constitution grants the federal government.", 2),
  makeQuestion(3, "kaplan-pretest-ss-practice-3-4", choices.p3, "A", "A. The FDA’s new regulations would place a financial hardship on small food retailers.", "The passage says smaller food retailers would feel more of the financial burden and describes proposed legislation intended to relieve it.", 2),
  makeQuestion(4, "kaplan-pretest-ss-practice-3-4", choices.p4, "C", "C. “devastating”", "The word devastating highlights the author’s view that the regulations would be especially harmful to smaller food retailers.", 3),
  makeQuestion(5, "kaplan-pretest-ss-practice-5-6", choices.p5, "D", "D. The argument is invalid, because it attempts to refute one reason against doing something while ignoring other possible reasons.", "The paragraph calls danger to the porcupine caribou one commonly cited reason against drilling, implying that other reasons may exist; refuting one reason does not support the broad conclusion that there is no reason not to drill.", 4),
  makeQuestion(6, "kaplan-pretest-ss-practice-5-6", choices.p6, "A", "A. Some people depend on the porcupine caribou for food.", "The argument relies on natural extinction evidence but does not address how drilling could affect people who depend on the caribou for food.", 4),
  makeQuestion(7, "kaplan-pretest-ss-practice-7-8", choices.p7, "B", "B. The map shows that most of the Warsaw Pact countries lay between the Soviet Union and Western countries, including France, West Germany, and Great Britain.", "Most Warsaw Pact countries were geographically between the Soviet Union and Western countries, supporting the idea that the pact created a buffer.", 5),
  makeQuestion(8, "kaplan-pretest-ss-practice-7-8", choices.p8, "A", "A. In forming the Warsaw Pact, the Soviet Union greatly increased its access to oceanic coastline.", "Although several member countries touched water, most borders were land borders and two member countries were landlocked, so the map disputes a major increase in ocean access.", 6),
  makeQuestion(9, "kaplan-pretest-ss-practice-9", choices.p9, "B", "B. 41", "The three northernmost states are Maine, New Hampshire, and Vermont. Their rainfall average is (41 + 42 + 39) ÷ 3 = 40.67, which rounds to 41 inches.", 7),
  makeQuestion(10, "kaplan-pretest-ss-practice-10", choices.p10, "B", "B. steadily increased, surpassing that of white voters in the 2012 elections", "The graph’s black-voter line increases consistently and is highest among the groups shown in 2012.", 8),
  makeQuestion(1, "kaplan-pretest-ss-content-1-2", choices.c1, "B", "B. the West Indies to the British colonies; the British colonies to Africa; Africa to the West Indies", "The map shows sugar and molasses moving from the West Indies to North America, rum moving from the British colonies to Africa, and gold and enslaved people moving from Africa to the West Indies.", 9),
  makeQuestion(2, "kaplan-pretest-ss-content-1-2", choices.c2, "A", "A. Cargo ships never had to sail empty on any leg of a profitable triangular journey.", "This is a general conclusion supported by the map’s details showing goods traveling along each leg; the other choices describe details that may be read directly from the map.", 10),
  makeQuestion(3, "kaplan-pretest-ss-content-3", choices.c3, "B", "B. commercial bank", "Commercial banks provide services and loans to businesses and corporations, while the other descriptions focus on national financial systems, consumers, or members.", 11),
  makeQuestion(4, "kaplan-pretest-ss-content-4-5", choices.c4, "B", "B. tainted system", "Tainted is a loaded word that communicates the author’s belief that the strong-mayor system is inherently corrupt.", 11),
  makeQuestion(5, "kaplan-pretest-ss-content-4-5", choices.c5, "D", "D. No, because no indication is given that the current mayor will behave as past mayors did.", "A strong-mayor system may enable corruption but does not guarantee it; past corruption alone does not justify strong suspicion of the current mayor.", 12),
  makeQuestion(6, "kaplan-pretest-ss-content-6", choices.c6, "D", "D. serving on a jury", "Serving on a jury is a civic duty and a way to participate in the judicial branch of government.", 12),
  makeQuestion(7, "kaplan-pretest-ss-content-7", choices.c7, "D", "D. law and order", "Military rule is characterized by strict control over the population, which reflects an emphasis on law and order.", 12),
  makeQuestion(8, "kaplan-pretest-ss-content-8-9", choices.c8, "C", "C. The French president has the power to dissolve the legislature, while the U.S. president does not.", "The chart shows a checkmark for dissolving the legislature under France but not under the United States.", 13),
  makeQuestion(9, "kaplan-pretest-ss-content-8-9", choices.c9, "B", "B. Of all the presidents shown, the French president has the greatest variety of powers.", "This is a generalization based on the chart’s details; the other choices are individual details shown in the chart.", 13),
  makeQuestion(10, "kaplan-pretest-ss-content-10", choices.c10, "D", "D. The U.S. Supreme Court ruling in Plessy v. Ferguson was wrong because it infringed on freedoms guaranteed in the Constitution.", "This statement restates the dissenting justice’s opinion. The other statements are factual claims from the passage.", 14),
  makeQuestion(11, "kaplan-pretest-ss-content-11-12", choices.c11, "A", "A. The nation’s debt increased at a faster rate than did the U.S. population during the period shown on the graph.", "Per capita debt rose steadily from 1990 to 2010, which indicates total debt grew faster than the population.", 15),
  makeQuestion(12, "kaplan-pretest-ss-content-11-12", choices.c12, "D", "D. raise taxes and cut spending", "Reducing debt requires increasing government income and lowering government costs.", 15),
  makeQuestion(13, "kaplan-pretest-ss-content-13", choices.c13, "C", "C. A drought was significantly worsened due to lack of native vegetation.", "The passage says deforestation caused a significant portion of the drought associated with the Mayan collapse.", 16),
  makeQuestion(14, "kaplan-pretest-ss-content-14", choices.c14, "C", "C. Many cities had large populations because nearby coal and iron ore deposits meant jobs.", "Comparing city locations with coalfields and iron ore deposits supports this conclusion; the other statements are direct map details.", 17),
  makeQuestion(15, "kaplan-pretest-ss-content-15", choices.c15, "B", "B. Great Britain’s acceptance of Germany’s takeover of Austria and Czechoslovakia in the late 1930s", "This is the only choice describing a concession to an aggressor without opposition, the hallmark of appeasement.", 18),
  makeQuestion(16, "kaplan-pretest-ss-content-16-18", choices.c16, "D", "D. People value the lives of their children more than they value money.", "The poster appeals to guilt by contrasting Americans’ willingness to risk their sons’ lives with their reluctance to donate money for the war.", 18),
  makeQuestion(17, "kaplan-pretest-ss-content-16-18", choices.c17, "B", "B. World War I", "The poster is dated 1917, during World War I.", 18),
  makeQuestion(18, "kaplan-pretest-ss-content-16-18", choices.c18, "D", "D. ads on social media", "Online advertising and social media would likely reach more people today than posters, leaflets, or print ads.", 18),
  makeQuestion(19, "kaplan-pretest-ss-content-19", choices.c19, "D", "D. The population of the colony of New York was smaller than that of Connecticut.", "Because the table lists the five most populous colonies and Connecticut is fifth, any unlisted colony, including New York, had a smaller population.", 19),
  makeQuestion(20, "kaplan-pretest-ss-content-20-22", choices.c20, "C", "C. Applying for Civil Service Jobs", "The title best describes the sequence of steps shown in the flowchart.", 20),
  makeQuestion(21, "kaplan-pretest-ss-content-20-22", choices.c21, "A", "A. salary", "A GS rating based on the job and the applicant’s skills and experience is directly related to the salary level.", 21),
  makeQuestion(22, "kaplan-pretest-ss-content-20-22", choices.c22, "B", "B. equal opportunity", "Civil Service jobs are awarded on merit and are open regardless of political affiliation or other personal factors, reflecting equal opportunity.", 21),
  makeQuestion(23, "kaplan-pretest-ss-content-23-24", choices.c23, "C", "C. 6 percent and $12,000 billion", "At 2005, the first graph is about 6 percent and the second graph is about $12,000 billion.", 22),
  makeQuestion(24, "kaplan-pretest-ss-content-23-24", choices.c24, "D", "D. As interest rates rise and then fall, the total mortgage debt will move similarly but not at the same rate.", "The graphs show similar overall movement, but mortgage debt changes at a different rate from mortgage interest rates.", 22),
  makeQuestion(25, "kaplan-pretest-ss-content-25", choices.c25, "D", "D. Hollywood, California, which produces movies and television shows, enjoyed around the world", "Hollywood’s globally distributed movies and television shows spread American popular culture worldwide.", 23),
];
