export const supplementalBatterySocialStudiesGroups = [
  {
    id: "battery-ss-1-3",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 1,
    questionEnd: 3,
    rangeLabel: "Battery Social Studies · Questions 1–3",
    contextType: "chart",
    marker: "Questions 1–3 are based on the following chart.",
    context: "Amendments to the U.S. Constitution\n\n1. Guarantees freedom of religion, speech, assembly, and press, and the right to petition the government\n2. Protects the rights of states to maintain a militia and of citizens to bear arms\n3. Restricts the quartering of troops in private homes\n4. Protects against unreasonable searches and seizures\n5. Assures the right not to be deprived of life, liberty, and property without due process of law\n6. Guarantees the right to a speedy and public trial by an impartial jury\n7. Assures the right to a jury trial in cases involving common law\n8. Protects against excessive bail or cruel and unusual punishment\n9. Provides that people’s rights are not restricted to those specified in the first eight amendments\n10. Reserves powers not granted to the national government to the states and the people",
    sourcePages: [2, 2],
    visualPage: 3002,
    questions: [
      { number: 1, text: "The chart above lists the first 10 amendments to the United States Constitution. The First Amendment includes" },
      { number: 2, text: "Amendments four to eight are referred to as" },
      { number: 3, text: "In the Third Amendment, the word quartering means which of the following?" },
    ],
  },
  {
    id: "battery-ss-4",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 4,
    questionEnd: 4,
    rangeLabel: "Battery Social Studies · Question 4",
    contextType: "graph",
    marker: "Question 4 is based on the following graph.",
    context: "2013 Value of Having $50.00 in Selected Prior Years\n\nThe graph compares the 2013 purchasing power of $50 held in earlier years, with points for 1960, 1970, 1980, 1990, 2000, and 2010. Source: Federal Bureau of Labor Statistics.",
    sourcePages: [3, 3],
    visualPage: 3003,
    questions: [{ number: 4, text: "According to the graph above, which decade experienced the fastest rate of inflation?" }],
  },
  {
    id: "battery-ss-5-6",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 5,
    questionEnd: 6,
    rangeLabel: "Battery Social Studies · Questions 5–6",
    contextType: "graph",
    marker: "Questions 5–6 are based on the following graph.",
    context: "Number of Slaves, 1850–1860\n\nThe bar graph compares the number of enslaved people in Virginia, South Carolina, Mississippi, and Alabama in 1850 and 1860. The bars show that Virginia’s totals were nearly equal, while Mississippi had the greatest increase by 1860.",
    sourcePages: [4, 4],
    visualPage: 3004,
    questions: [
      { number: 5, text: "According to this graph, which state had almost as many slaves in 1850 as it did in 1860?" },
      { number: 6, text: "According to the graph, which state had the greatest increase in the number of slaves in 1860?" },
    ],
  },
  {
    id: "battery-ss-7",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 7,
    questionEnd: 7,
    rangeLabel: "Battery Social Studies · Question 7",
    contextType: "graph",
    marker: "Question 7 is based on the following graph.",
    context: "Decrease in Housing Market Due to Unemployment\n\nThe graph compares unemployment, decline in the housing market, and foreclosures from 2008 through 2011. Source: U.S. Bureau of Labor and Statistics.",
    sourcePages: [5, 5],
    visualPage: 3005,
    questions: [{ number: 7, text: "Which of the following statements is supported by the graph?" }],
  },
  {
    id: "battery-ss-8",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 8,
    questionEnd: 8,
    rangeLabel: "Battery Social Studies · Question 8",
    contextType: "map",
    marker: "Question 8 is based on the following map.",
    context: "Status of the States, 1861\n\nThe map distinguishes states that seceded before April 15, 1861, states that seceded after that date, Union states that permitted slavery, Union states that banned slavery, and territories.",
    sourcePages: [6, 6],
    visualPage: 3006,
    questions: [{ number: 8, text: "According to the above map, April 15, 1861 was significant. What conclusion can be made about this date?" }],
  },
  {
    id: "battery-ss-9-10",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 9,
    questionEnd: 10,
    rangeLabel: "Battery Social Studies · Questions 9–10",
    contextType: "passage",
    marker: "Questions 9–10 are based on the following historical letter.",
    context: "George W. Harkins to the American People, February 25, 1832\n\nThis letter, printed widely in American newspapers, was written by George W. Harkins, chief of the Choctaw tribe, in response to the forced removal of Indigenous people to new homes in the West. Harkins rejects the claim that the Choctaw’s movement was voluntary and asks for justice and rest for his people. Courtesy of the Center on Congress at Indiana University.",
    sourcePages: [7, 7],
    questions: [
      { number: 9, text: "In his letter, George W. Harkins is referring to which of the following?" },
      { number: 10, text: "Which conclusion can you draw from the information in the Harkins letter?" },
    ],
  },
  {
    id: "battery-ss-11",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 11,
    questionEnd: 11,
    rangeLabel: "Battery Social Studies · Question 11",
    contextType: "map",
    marker: "Question 11 is based on the following map.",
    context: "The map identifies major deserts around the world, including the Great Basin, Peruvian, Atacama, Patagonian, Sahara, Arabian, Turkestan, Great Indian, Gobi, Kalahari, and Namib deserts.",
    sourcePages: [8, 8],
    visualPage: 3008,
    questions: [{ number: 11, text: "Based on the map, which of the following is the most likely conclusion one could draw?" }],
  },
  {
    id: "battery-ss-12-13",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 12,
    questionEnd: 13,
    rangeLabel: "Battery Social Studies · Questions 12–13",
    contextType: "table",
    marker: "Questions 12–13 are based on the following information and table.",
    context: "The Constitution allows the federal government and the states to exercise some nearly identical powers. Both can make and enforce similar laws, levy taxes, charter banks, and borrow money. Powers that exist at both levels are called concurrent powers.\n\nFederal powers include declaring war, regulating interstate and foreign trade, coining money, establishing post offices, admitting new states, establishing foreign policy, and making laws for citizenship. Shared powers include enforcing laws, borrowing money, levying taxes, chartering banks, providing for the general welfare, and establishing schools. Powers reserved to the states include establishing local governments, regulating commerce within a state, providing for public safety, making marriage laws, and assuming powers not granted to the federal government.",
    sourcePages: [9, 9],
    visualPage: 3009,
    questions: [
      { number: 12, text: "Which of the following are shared powers of the Federal and State governments?" },
      { number: 13, text: "In the introduction to this chart the word concurrent most likely means which of the following?" },
    ],
  },
  {
    id: "battery-ss-14",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 14,
    questionEnd: 14,
    rangeLabel: "Battery Social Studies · Question 14",
    contextType: "table",
    marker: "Question 14 is based on the following table.",
    context: "Trends in Urban Populations—Current and Projected\n\nThe table ranks the world’s most populous urban areas in 1975, 2000, and 2025. Tokyo appears first in all three columns; Bombay and Delhi are projected to rise in the 2025 ranking. Source: United Nations, World Urbanization Prospects, The 2007 Revision.",
    sourcePages: [10, 10],
    visualPage: 3010,
    questions: [{ number: 14, text: "Based on the information in the chart above, which city will be the most populous city in the world in 2025?" }],
  },
  {
    id: "battery-ss-15-16",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 15,
    questionEnd: 16,
    rangeLabel: "Battery Social Studies · Questions 15–16",
    contextType: "chart",
    marker: "Questions 15–16 are based on the following pie chart.",
    context: "Refugees in the United States in 2010\n\nThe chart shows refugees from the Near East and South Asia at 34%, Iraq at 17%, East Asia at 17%, Bhutanese at 12%, Africa at 12%, Latin America and the Caribbean at 5%, and Iran at 3%.",
    sourcePages: [11, 11],
    visualPage: 3011,
    questions: [
      { number: 15, text: "According to the graph, what conclusion can be made about refugees in the United States in 2010?" },
      { number: 16, text: "The smallest number of refugees in the United States came from which place or places?" },
    ],
  },
  {
    id: "battery-ss-17-19",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 17,
    questionEnd: 19,
    rangeLabel: "Battery Social Studies · Questions 17–19",
    contextType: "timeline",
    marker: "Questions 17–19 are based on the following information and amendment excerpt.",
    context: "Text 1: The Aftermath of the Alien and Sedition Acts\n\nIn 1798, Congress passed the Alien and Sedition Acts amid fears of war with France. The Alien Act allowed the president to imprison or expel non-citizens deemed dangerous, while the Sedition Act restricted speech critical of the government. Thomas Jefferson and James Madison argued that the federal government lacked powers not specifically granted by the Constitution. Kentucky and Virginia adopted resolutions asserting states’ rights, and the election of 1800 ended in a tie that the House of Representatives had to resolve. Jefferson ultimately won, and the 12th Amendment was later added.\n\nText 2: Amendment XII\n\nIf no presidential candidate receives a majority of electoral votes, the House of Representatives chooses from the leading candidates, with each state delegation receiving one vote.",
    sourcePages: [11, 13],
    visualPage: 3012,
    questions: [
      { number: 17, text: "Place the four events into the flow chart to show the order in which they occur in Text 1." },
      { number: 18, text: "In the text, the word nullify most likely means which of the following?" },
      { number: 19, text: "The 12th Amendment was one important result of the election of 1800. According to the excerpt, what was the purpose of passing this amendment?" },
    ],
  },
  {
    id: "battery-ss-20-21",
    section: "Social Studies",
    topic: "World History",
    questionStart: 20,
    questionEnd: 21,
    rangeLabel: "Battery Social Studies · Questions 20–21",
    contextType: "map",
    marker: "Questions 20–21 are based on the following map.",
    context: "The Fertile Crescent is the productive arc of land between the Mediterranean Sea and the Persian Gulf. The map identifies the Tigris and Euphrates rivers within this region.",
    sourcePages: [13, 13],
    visualPage: 3013,
    questions: [
      { number: 20, text: "The area on the map above is known as the Fertile Crescent. What is the reason for this name?" },
      { number: 21, text: "The Fertile Crescent is between the ______ and the ______ rivers." },
    ],
  },
  {
    id: "battery-ss-22-23",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 22,
    questionEnd: 23,
    rangeLabel: "Battery Social Studies · Questions 22–23",
    contextType: "passage",
    marker: "Questions 22–23 are based on the following passage.",
    context: "In Marbury v. Madison, John Adams made last-minute appointments before leaving office, but President Jefferson ordered James Madison not to deliver William Marbury’s appointment papers. Chief Justice John Marshall ruled that Marbury had no right to appeal under the relevant law and, for the first time, the Supreme Court ruled a law unconstitutional. The decision established the principle of judicial review.",
    sourcePages: [14, 14],
    visualPage: null,
    questions: [
      { number: 22, text: "Marbury v. Madison is one of the most important Supreme Court rulings in United States history. Why was this ruling so significant?" },
      { number: 23, text: "The process established in the case of Marbury v. Madison is called judicial review. It extends the power of the ______ branch of U.S. government." },
    ],
  },
  {
    id: "battery-ss-24",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 24,
    questionEnd: 24,
    rangeLabel: "Battery Social Studies · Question 24",
    contextType: "standalone",
    marker: "Question 24 concerns globalization and international organizations.",
    context: "Mass demonstrations against globalization often targeted large international organizations.",
    sourcePages: [15, 15],
    questions: [{ number: 24, text: "What organization was often the target of mass demonstrations, a few of them violent, against globalization?" }],
  },
  {
    id: "battery-ss-25",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 25,
    questionEnd: 25,
    rangeLabel: "Battery Social Studies · Question 25",
    contextType: "chart",
    marker: "Question 25 is based on the following chart.",
    context: "Number of Americans by Type of Health Insurance Coverage, in millions, comparing 2010 and 2011 across employer-sponsored, individual, Medicare, Medicaid, and uninsured categories.",
    sourcePages: [15, 15],
    visualPage: 3015,
    questions: [{ number: 25, text: "Based on the information in this chart, what are the implications concerning health insurance?" }],
  },
  {
    id: "battery-ss-26-27",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 26,
    questionEnd: 27,
    rangeLabel: "Battery Social Studies · Questions 26–27",
    contextType: "passage",
    marker: "Questions 26–27 are based on the following statements and passage.",
    context: "The Great Recession triggered a large increase in the number of Americans without health insurance from 2008 to 2010 as job losses caused people to lose employer-sponsored coverage. The Affordable Care Act, signed in 2010, had the goal of reducing the number of uninsured.\n\nThe Fair Credit Reporting Act requires Equifax, Experian, and TransUnion to provide a free credit report once every 12 months. A credit report includes where you live, how you pay your bills, whether you have been sued or filed for bankruptcy, and information used by creditors, insurers, employers, and landlords. The Act promotes accuracy and privacy and is enforced by the Federal Trade Commission.",
    sourcePages: [16, 16],
    questions: [
      { number: 26, text: "Based on the statement, what would be a reasonable prediction for 2011 about the rate of uninsured in relation to the total American population?" },
      { number: 27, text: "According to the excerpt, what information is found in your credit report?" },
    ],
  },
  {
    id: "battery-ss-28-30",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 28,
    questionEnd: 30,
    rangeLabel: "Battery Social Studies · Questions 28–30",
    contextType: "passage",
    marker: "Questions 28–30 are based on the Sixth Amendment.",
    context: "In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial by an impartial jury of the state and district wherein the crime was committed, to be informed of the accusation, to confront witnesses, to obtain witnesses in the accused’s favor, and to have the assistance of counsel. Source: National Archives and Records Administration.",
    sourcePages: [17, 17],
    questions: [
      { number: 28, text: "Which of the following is NOT provided for in the Sixth Amendment?" },
      { number: 29, text: "As it is used in the above text, what does the word impartial mean?" },
      { number: 30, text: "Some trials do not take place in the district wherein the crime was committed when the attorney of the accused asks for a change of venue. What does the term change of venue mean?" },
    ],
  },
  {
    id: "battery-ss-31",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 31,
    questionEnd: 31,
    rangeLabel: "Battery Social Studies · Question 31",
    contextType: "map",
    marker: "Question 31 is based on a map of Hernando de Soto’s exploration route.",
    context: "The map shows the March of De Soto and his men from 1539–1544 across the southeastern region of what is now the United States. Source: Library of Congress.",
    sourcePages: [18, 18],
    visualPage: 3018,
    questions: [{ number: 31, text: "Based on the map, Hernando de Soto explored the ______ regions of the United States." }],
  },
  {
    id: "battery-ss-32-34",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 32,
    questionEnd: 34,
    rangeLabel: "Battery Social Studies · Questions 32–34",
    contextType: "graph",
    marker: "Questions 32–34 are based on the following chart.",
    context: "Number of Unemployed—25 Years and Older, by Level of Education, in millions. Categories are less than high school diploma, high school diploma, some college, and bachelor’s degree or more. The chart compares 2012 and 2013. Source: Bureau of Labor Statistics, April 2013.",
    sourcePages: [19, 19],
    visualPage: 3019,
    questions: [
      { number: 32, text: "Based on the information in the chart, ______ people with high school diplomas are unemployed than those with a bachelor’s degree." },
      { number: 33, text: "Based on the information in the chart, the best prediction about the unemployment rate for people over 25 years old is that it ______ in 2013 when compared to 2012." },
      { number: 34, text: "Which of the following conclusions about the connection between education level and unemployment rate is best supported by the data in the chart?" },
    ],
  },
  {
    id: "battery-ss-35",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 35,
    questionEnd: 35,
    rangeLabel: "Battery Social Studies · Question 35",
    contextType: "passage",
    marker: "Question 35 is based on President Reagan’s 1986 State of the Union message.",
    context: "President Reagan’s 1986 State of the Union address was postponed after the Challenger explosion on January 28, 1986. In the address he paid tribute to the seven crew members and reaffirmed the nation’s commitment to the space program. Source: Records of the U.S. Senate.",
    sourcePages: [20, 21],
    questions: [{ number: 35, text: "This document refers to the Challenger explosion several times. Based on the information in the text, which of the following describes the Challenger?" }],
  },
  {
    id: "battery-ss-36",
    section: "Social Studies",
    topic: "Economics",
    questionStart: 36,
    questionEnd: 36,
    rangeLabel: "Battery Social Studies · Question 36",
    contextType: "chart",
    marker: "Question 36 is based on the following information.",
    context: "The United States’ involvement in war has become increasingly expensive as technology improved. The American Revolution cost $101 million, the War of 1812 cost $90 million, the Civil War cost an estimated $5 billion, World War I cost $20 billion, and World War II cost $296 billion.",
    sourcePages: [21, 22],
    visualPage: 3022,
    questions: [{ number: 36, text: "Which of the following graphics supports the information in the paragraph?" }],
  },
  {
    id: "battery-ss-37",
    section: "Social Studies",
    topic: "Geography",
    questionStart: 37,
    questionEnd: 37,
    rangeLabel: "Battery Social Studies · Question 37",
    contextType: "map",
    marker: "Question 37 is based on the following map.",
    context: "The map displays per capita personal income by state in 2011 using shaded income ranges. Source: U.S. Bureau of Economic Analysis.",
    sourcePages: [23, 23],
    visualPage: 3023,
    questions: [{ number: 37, text: "Based on the map, the states with the lowest per capita personal income in 2011 were found in which of the following locations?" }],
  },
  {
    id: "battery-ss-38-39",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 38,
    questionEnd: 39,
    rangeLabel: "Battery Social Studies · Questions 38–39",
    contextType: "chart",
    marker: "Questions 38–39 are based on the Department of Homeland Security information graphic.",
    context: "After September 11, 2001, the Department of Homeland Security was created to prevent terrorism and protect the public from terrorism, natural disasters, cyber attacks, and other emergencies. Its work includes airport screening, border and cargo inspection, disaster grants, emergency response, cyber-security, and protection of government officials.",
    sourcePages: [24, 26],
    visualPage: 3024,
    questions: [
      { number: 38, text: "Based on the information, which of the following would be an area Homeland Security would investigate?" },
      { number: 39, text: "As used in the excerpt, the word vigilance most likely can be defined by which of the following?" },
    ],
  },
  {
    id: "battery-ss-40-41",
    section: "Social Studies",
    topic: "World History",
    questionStart: 40,
    questionEnd: 41,
    rangeLabel: "Battery Social Studies · Questions 40–41",
    contextType: "chart",
    marker: "Questions 40–41 are based on the following chart and graph.",
    context: "The Transatlantic Slave Trade, 1451–1870\n\nThe chart and graph compare the number of enslaved people transported to British North America, Spanish America, Caribbean islands, Portuguese Brazil, and Europe, Africa, and Asia across four periods: 1451–1600, 1601–1700, 1701–1810, and 1811–1870.",
    sourcePages: [26, 27],
    visualPage: 3026,
    questions: [
      { number: 40, text: "According to the chart and graph, the transportation of slaves increased sharply in which of the following areas?" },
      { number: 41, text: "The slave trade drastically decreased in British North America. Which of the following is the best explanation for this drop in numbers in 1811–1870?" },
    ],
  },
  {
    id: "battery-ss-42-43",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 42,
    questionEnd: 43,
    rangeLabel: "Battery Social Studies · Questions 42–43",
    contextType: "map",
    marker: "Questions 42–43 are based on a passage and map about the Louisiana Purchase.",
    context: "Robert Livingston and James Monroe signed the Louisiana Purchase Treaty in Paris on April 30, 1803. The United States purchased the Louisiana Territory from France for $15 million, adding 828,000 square miles west of the Mississippi River. President Thomas Jefferson was a strict interpreter of the Constitution and questioned whether the federal government was authorized to acquire new territory, but he also wanted an ‘empire for liberty’ across the continent.",
    sourcePages: [28, 28],
    visualPage: 3028,
    questions: [
      { number: 42, text: "President Jefferson was reluctant to agree to the purchase of the Louisiana Territory because" },
      { number: 43, text: "Jefferson was a Democratic-Republican. When the Federalists learned about the Louisiana Purchase, they were upset. Which of the following can be inferred about the reason the Federalists were upset?" },
    ],
  },
  {
    id: "battery-ss-44-46",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 44,
    questionEnd: 46,
    rangeLabel: "Battery Social Studies · Questions 44–46",
    contextType: "passage",
    marker: "Questions 44–46 are based on the following passage about woman suffrage.",
    context: "The woman suffrage movement was first seriously proposed at Seneca Falls in 1848. Early leaders, including Susan B. Anthony, Elizabeth Cady Stanton, Lucretia Mott, Lucy Stone, and others, were also advocates of temperance and abolition. Suffragists formed organizations, held meetings, worked through state legislatures, challenged exclusion in the courts, and used protest and civil disobedience. Susan B. Anthony attempted to vote in 1872 and was arrested, convicted, and fined. The 19th Amendment granted nationwide suffrage to women in 1920. Source: National Archives and Records Administration.",
    sourcePages: [29, 30],
    questions: [
      { number: 44, text: "According to the excerpt, Suffragettes were involved in several other movements as well. Which of the following includes the other causes these women championed?" },
      { number: 45, text: "According to the excerpt, the women suffragists used several methods to gain attention for their cause. Enter the correct methods, separated by commas. The correct items were formed organizations, held meetings, and went to the courts." },
      { number: 46, text: "Which suffragist made a daring attempt to challenge the denial of women’s vote by attempting to vote anyway? She was arrested, convicted, and fined." },
    ],
  },
  {
    id: "battery-ss-47",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 47,
    questionEnd: 47,
    rangeLabel: "Battery Social Studies · Question 47",
    contextType: "passage",
    marker: "Question 47 is based on a passage about the Watergate scandal.",
    context: "In June 1972, five men broke into the Democratic National Committee headquarters in the Watergate office building. The media discovered that those arrested were connected to the committee to reelect the president, including one White House worker. During the investigation, White House staff took steps to hide evidence, and the Supreme Court case United States v. Richard M. Nixon followed before Nixon resigned.",
    sourcePages: [31, 31],
    questions: [{ number: 47, text: "After reading the passage, arrange the following information in the order of the events which led to the resignation of President Richard Nixon. Enter the letters in order, separated by commas: A. cover-up steps, B. Supreme Court case of United States v. Richard Nixon, C. discovery that White House staff members were involved, D. break-in at the Democratic National Committee headquarters." }],
  },
  {
    id: "battery-ss-48",
    section: "Social Studies",
    topic: "U.S. History",
    questionStart: 48,
    questionEnd: 48,
    rangeLabel: "Battery Social Studies · Question 48",
    contextType: "standalone",
    marker: "Question 48 is based on a quotation by Franklin D. Roosevelt.",
    context: "“It is common sense to take a method and try it. If it fails, admit it frankly and try another. But above all, try something.” — Franklin D. Roosevelt",
    sourcePages: [31, 31],
    questions: [{ number: 48, text: "Which of the following is President Roosevelt referring to in the above quote?" }],
  },
  {
    id: "battery-ss-49",
    section: "Social Studies",
    topic: "Civics and Government",
    questionStart: 49,
    questionEnd: 49,
    rangeLabel: "Battery Social Studies · Question 49",
    contextType: "standalone",
    marker: "Question 49 concerns a constitutional remedy for improper imprisonment.",
    context: "The writ of habeas corpus is used to challenge unlawful detention and seek the release of someone imprisoned without due process of law.",
    sourcePages: [31, 31],
    questions: [{ number: 49, text: "Which of the following is used to release a person from improper imprisonment?" }],
  },
] as const;

const choices = {
  q1: [
    { label: "A", text: "the Rights of the Accused" },
    { label: "B", text: "the Five Freedoms" },
    { label: "C", text: "the Preamble" },
    { label: "D", text: "the Bill of Rights" },
  ],
  q2: [
    { label: "A", text: "the Rights of the Accused" },
    { label: "B", text: "the Five Freedoms" },
    { label: "C", text: "the Preamble" },
    { label: "D", text: "the Bill of Rights" },
  ],
  q3: [
    { label: "A", text: "cutting" },
    { label: "B", text: "blocking" },
    { label: "C", text: "housing" },
    { label: "D", text: "measuring" },
  ],
  q4: [
    { label: "A", text: "1960s" },
    { label: "B", text: "1970s" },
    { label: "C", text: "1980s" },
    { label: "D", text: "1990s" },
  ],
  q7: [
    { label: "A", text: "The unemployment rate increased from 2008 to 2011, causing the number of foreclosures to increase." },
    { label: "B", text: "The unemployment rate remained steady from 2009 to 2011; however, the decrease in the housing market increased." },
    { label: "C", text: "The unemployment rate, decline in housing market, and number of foreclosures are unrelated." },
    { label: "D", text: "Foreclosures increased steadily throughout the period between 2008 and 2011 with little or no correlation to the unemployment rate." },
  ],
  q8: [
    { label: "A", text: "The United States had a new president." },
    { label: "B", text: "The line drawn by the Missouri Compromise in 1850 did not apply to California." },
    { label: "C", text: "The territories did not have slavery." },
    { label: "D", text: "The Southern states had seceded from the Union." },
  ],
  q9: [
    { label: "A", text: "Indian Removal Act" },
    { label: "B", text: "Civil Rights Movement" },
    { label: "C", text: "American Indian Movement" },
    { label: "D", text: "People’s Protest at the University of California at Berkeley" },
  ],
  q10: [
    { label: "A", text: "The Choctaw tribe was leaving their lands voluntarily." },
    { label: "B", text: "The Choctaw tribe was being forced to leave their lands." },
    { label: "C", text: "The Choctaw tribe had no land." },
    { label: "D", text: "The Choctaw tribe wanted to move to another place." },
  ],
  q11: [
    { label: "A", text: "Most desertification occurs near the equator." },
    { label: "B", text: "A large area of desert can be found in Northern Africa." },
    { label: "C", text: "There is a large desert area in South America." },
    { label: "D", text: "There is no desert in Australia." },
  ],
  q12: [
    { label: "A", text: "Make it possible for an immigrant to become a citizen of the United States" },
    { label: "B", text: "Provide the legal basis and charter for a new bank in the state of Wyoming" },
    { label: "C", text: "Establish a new school system in Shelby County, Tennessee" },
    { label: "D", text: "Admit Puerto Rico as a new state" },
  ],
  q13: [
    { label: "A", text: "Next to one another" },
    { label: "B", text: "Shared by both federal and state" },
    { label: "C", text: "Occurring in two geographic places at the same time" },
    { label: "D", text: "Near but not next to one another" },
  ],
  q15: [
    { label: "A", text: "More than half the refugees in the United States were from Asia." },
    { label: "B", text: "Latin America and the Caribbean were a great source of refugees in 2010." },
    { label: "C", text: "Refugees come to the United States from Europe." },
    { label: "D", text: "Iran and Iraq had a large number of refugees." },
  ],
  q18: [
    { label: "A", text: "to bring about" },
    { label: "B", text: "to strike down" },
    { label: "C", text: "to add to the Constitution" },
    { label: "D", text: "to become higher in rank" },
  ],
  q19: [
    { label: "A", text: "To make Thomas Jefferson the president of the United States" },
    { label: "B", text: "To provide a way to decide who is president in the event of an equal number of votes" },
    { label: "C", text: "To help the House of Representatives make Thomas Jefferson the president" },
    { label: "D", text: "To give the electoral college more power" },
  ],
  q20: [
    { label: "A", text: "It is a place of large population" },
    { label: "B", text: "It is an area where people travel a great deal" },
    { label: "C", text: "It is between two rivers which makes the land very productive" },
    { label: "D", text: "It is a place where people migrate often" },
  ],
  q22: [
    { label: "A", text: "Denied Adams’s right to make midnight appointments" },
    { label: "B", text: "Upheld Adams’s right to make midnight appointments" },
    { label: "C", text: "Confirmed Congress’s power to expand judicial authority" },
    { label: "D", text: "Affirmed the power of the court to declare a law unconstitutional" },
  ],
  q24: [
    { label: "A", text: "WTO—World Trade Organization" },
    { label: "B", text: "CBC—Canadian Broadcasting Corporation" },
    { label: "C", text: "NATO—North Atlantic Treaty Organization" },
    { label: "D", text: "NASA—National Aeronautics and Space Administration" },
  ],
  q25: [
    { label: "A", text: "More people were insured in 2011 than in 2010." },
    { label: "B", text: "The number of uninsured have increased." },
    { label: "C", text: "The number of insured overall have increased." },
    { label: "D", text: "More people are insured by Medicare and Medicaid." },
  ],
  q26: [
    { label: "A", text: "Uninsured rates would be expected to rise as the economy improved and early provisions expanding coverage under the ACA went into effect." },
    { label: "B", text: "There would be no uninsured Americans left because, under the ACA, all Americans are mandated to carry health insurance." },
    { label: "C", text: "Newly insured Americans would place a strain on the Medicaid system." },
    { label: "D", text: "Uninsured rates would be expected to drop as the economy improved and early provisions expanding coverage under the ACA went into effect." },
  ],
  q27: [
    { label: "A", text: "your education level, income amount, and debt amounts" },
    { label: "B", text: "your payment and credit history" },
    { label: "C", text: "your parents’ or other family members’ credit history" },
    { label: "D", text: "your bank account numbers" },
  ],
  q28: [
    { label: "A", text: "A mistrial" },
    { label: "B", text: "An innocent person convicted of crimes he did not commit" },
    { label: "C", text: "A lengthy trial" },
    { label: "D", text: "The services of an attorney" },
  ],
  q29: [
    { label: "A", text: "half" },
    { label: "B", text: "fair" },
    { label: "C", text: "long" },
    { label: "D", text: "large" },
  ],
  q30: [
    { label: "A", text: "More people to select as jurors" },
    { label: "B", text: "A different location for the trial since it may be difficult to find an impartial jury in the area the crime was committed" },
    { label: "C", text: "A larger location in the event of a large attendance" },
    { label: "D", text: "A different attorney since the accused cannot pay" },
  ],
  q34: [
    { label: "A", text: "Education will not make a difference in the unemployment rate for people in the future." },
    { label: "B", text: "Education plays a significant role in finding and keeping a job now and in the future." },
    { label: "C", text: "People who have less than a high school diploma can get good paying jobs." },
    { label: "D", text: "People with a high school diploma do not need to further their education in order to find and keep jobs." },
  ],
  q35: [
    { label: "A", text: "an airplane crash" },
    { label: "B", text: "a war mission in Cuba" },
    { label: "C", text: "a space shuttle" },
    { label: "D", text: "a missile launched, but failed to fire" },
  ],
  q36: [
    { label: "A", text: "A graphic showing costs that do not increase over time" },
    { label: "B", text: "A graphic that includes Vietnam but omits the wars listed in the paragraph" },
    { label: "C", text: "A graphic that correctly shows the listed wars and their increasing costs" },
    { label: "D", text: "A graphic showing only the dates of the wars" },
  ],
  q37: [
    { label: "A", text: "north and west" },
    { label: "B", text: "northeast" },
    { label: "C", text: "no specific area, but all parts of the nation" },
    { label: "D", text: "around large cities" },
  ],
  q38: [
    { label: "A", text: "searching for drug smugglers in Mexico" },
    { label: "B", text: "going to Iran to find terrorist groups" },
    { label: "C", text: "providing assistance after an earthquake in California" },
    { label: "D", text: "investigating a shooting in Peru" },
  ],
  q39: [
    { label: "A", text: "a religious ritual" },
    { label: "B", text: "an alert watchfulness" },
    { label: "C", text: "a long ceremony" },
    { label: "D", text: "an attack on the country" },
  ],
  q40: [
    { label: "A", text: "Europe" },
    { label: "B", text: "the United States" },
    { label: "C", text: "Spanish America" },
    { label: "D", text: "British North America" },
  ],
  q41: [
    { label: "A", text: "There were no more Africans to become slaves." },
    { label: "B", text: "There were no crops or work for which slave labor was needed." },
    { label: "C", text: "Great Britain abolished slavery in all of its colonies." },
    { label: "D", text: "Spanish America had more resources to purchase and transport slaves." },
  ],
  q42: [
    { label: "A", text: "He was unsure the Constitution allowed him to make the agreement." },
    { label: "B", text: "He was afraid the Indians would be upset." },
    { label: "C", text: "He thought New Orleans would become a large trade center and difficult to control since it was so far from Washington, D.C." },
    { label: "D", text: "Spain had claimed the area as theirs, so Jefferson feared it might cause a war with Spain." },
  ],
  q43: [
    { label: "A", text: "The Federalists thought the British were involved in the deal." },
    { label: "B", text: "The Federalists feared more slave states would enter the Union." },
    { label: "C", text: "The Federalists were concerned that more states would become Republican." },
    { label: "D", text: "The Federalists understood that the Constitution did not authorize the purchase." },
  ],
  q44: [
    { label: "A", text: "war protests" },
    { label: "B", text: "environmental protests" },
    { label: "C", text: "temperance and abolition of slavery" },
    { label: "D", text: "world peace" },
  ],
  q46: [
    { label: "A", text: "Elizabeth Cady Stanton" },
    { label: "B", text: "Lucy Stone" },
    { label: "C", text: "Virginia Minor" },
    { label: "D", text: "Susan B. Anthony" },
  ],
  q48: [
    { label: "A", text: "his plan for the future" },
    { label: "B", text: "his disability" },
    { label: "C", text: "his New Deal" },
    { label: "D", text: "his job as President" },
  ],
  q49: [
    { label: "A", text: "a writ of mandamus" },
    { label: "B", text: "a writ of habeas corpus" },
    { label: "C", text: "the Supreme Court’s decision in Roe v. Wade" },
    { label: "D", text: "ex post facto laws" },
  ],
} as const;

type AnswerRecord = {
  number: number;
  groupId: string;
  section: string;
  topic: string;
  reference: string;
  prompt: string;
  choices: readonly { label: string; text: string }[];
  correctLabel: string | null;
  answerLine: string;
  explanation: string;
  sourcePage: number;
};

const groupById = new Map<string, (typeof supplementalBatterySocialStudiesGroups)[number]>(supplementalBatterySocialStudiesGroups.map((group) => [group.id, group]));
const promptFor = (groupId: string, number: number) => groupById.get(groupId)?.questions.find((question) => question.number === number)?.text || "";
const makeQuestion = (number: number, groupId: string, choicesFor: readonly { label: string; text: string }[], correctLabel: string | null, answerLine: string, explanation: string, sourcePage: number): AnswerRecord => {
  const group = groupById.get(groupId);
  if (!group) throw new Error(`Unknown Battery Social Studies group: ${groupId}`);
  return { number, groupId, section: group.section, topic: group.topic, reference: "Battery Social Studies Practice Test 2", prompt: promptFor(groupId, number), choices: choicesFor, correctLabel, answerLine, explanation, sourcePage };
};

export const supplementalBatterySocialStudiesQuestions: readonly AnswerRecord[] = [
  makeQuestion(1, "battery-ss-1-3", choices.q1, "B", "B. The Five Freedoms", "The First Amendment contains the Five Freedoms: religion, speech, press, assembly, and petition.", 2),
  makeQuestion(2, "battery-ss-1-3", choices.q2, "A", "A. The Rights of the Accused", "Amendments four through eight address searches, due process, trials, juries, bail, and related rights of the accused.", 2),
  makeQuestion(3, "battery-ss-1-3", choices.q3, "C", "C. Housing", "In this context, quartering means housing soldiers in private homes.", 2),
  makeQuestion(4, "battery-ss-4", choices.q4, "C", "C. 1980s", "The supplied answer key marks the 1980s. Read the original graph alongside the answer key when reviewing this item.", 3),
  makeQuestion(5, "battery-ss-5-6", [], null, "Virginia", "Virginia’s 1850 and 1860 bars are almost equal in size.", 4),
  makeQuestion(6, "battery-ss-5-6", [], null, "Mississippi", "The 1860 bar for Mississippi shows the greatest increase among the states shown.", 4),
  makeQuestion(7, "battery-ss-7", choices.q7, "D", "D. Foreclosures increased steadily throughout the period between 2008 and 2011 with little or no correlation to the unemployment rate.", "The supplied explanation says the graph is inconclusive and does not establish a correlation between unemployment and the decline in the housing market.", 5),
  makeQuestion(8, "battery-ss-8", choices.q8, "D", "D. The Southern states had seceded from the Union.", "The map identifies the Southern states that had seceded from the Union by the date shown.", 6),
  makeQuestion(9, "battery-ss-9-10", choices.q9, "A", "A. Indian Removal Act", "Harkins’s letter concerns the forced removal of the Choctaw people, associated with the Indian Removal Act.", 7),
  makeQuestion(10, "battery-ss-9-10", choices.q10, "B", "B. The Choctaw tribe was being forced to leave their lands.", "Harkins rejects the claim that the Choctaw were leaving voluntarily and describes their expulsion.", 7),
  makeQuestion(11, "battery-ss-11", choices.q11, "B", "B. A large area of desert can be found in Northern Africa.", "The map supports the conclusion that a large desert area, the Sahara, is located in Northern Africa.", 8),
  makeQuestion(12, "battery-ss-12-13", choices.q12, "B", "B. Provide the legal basis and charter for a new bank in the state of Wyoming", "Chartering banks is listed among the powers shared by the federal and state governments.", 9),
  makeQuestion(13, "battery-ss-12-13", choices.q13, "B", "B. Shared by both federal and state", "The passage defines concurrent powers as powers that exist at both levels of government.", 9),
  makeQuestion(14, "battery-ss-14", [], null, "Tokyo", "Tokyo appears as the most populous city in the 2025 column of the table.", 10),
  makeQuestion(15, "battery-ss-15-16", choices.q15, "A", "A. More than half the refugees in the United States were from Asia.", "The Near East and South Asia total 34%, and East Asia adds 17%, for more than half together.", 11),
  makeQuestion(16, "battery-ss-15-16", [], null, "Iran, Latin America, and the Caribbean", "The chart shows Iran at 3% and Latin America and the Caribbean at 5%; the supplied answer key lists both places.", 11),
  makeQuestion(17, "battery-ss-17-19", [], null, "Congress passes the Alien and Sedition Acts, Virginia and Kentucky resolutions enacted, Election of 1800 ends in a tie, The 12th Amendment to the Constitution is ratified", "The order is: Congress passes the Acts; the Virginia and Kentucky resolutions are enacted; the election ends in a tie; the 12th Amendment is ratified.", 12),
  makeQuestion(18, "battery-ss-17-19", choices.q18, "B", "B. to strike down", "In the passage, nullify means to strike down or invalidate.", 13),
  makeQuestion(19, "battery-ss-17-19", choices.q19, "B", "B. To provide a way to decide who is president in the event of an equal number of votes", "The 12th Amendment clarified the procedure for resolving an Electoral College tie.", 13),
  makeQuestion(20, "battery-ss-20-21", choices.q20, "C", "C. It is between two rivers which makes the land very productive", "The Fertile Crescent is named for the productive land between the Tigris and Euphrates rivers.", 13),
  makeQuestion(21, "battery-ss-20-21", [], null, "Tigris and Euphrates", "The Tigris and Euphrates are the rivers identified in the Fertile Crescent map.", 13),
  makeQuestion(22, "battery-ss-22-23", choices.q22, "D", "D. Affirmed the power of the court to declare a law unconstitutional", "Marbury v. Madison affirmed the Supreme Court’s power of judicial review.", 14),
  makeQuestion(23, "battery-ss-22-23", [], null, "Judicial", "Judicial review allows a court to review a law and determine whether it is unconstitutional.", 14),
  makeQuestion(24, "battery-ss-24", choices.q24, "A", "A. WTO—World Trade Organization", "The World Trade Organization is the global organization listed among the choices.", 15),
  makeQuestion(25, "battery-ss-25", choices.q25, "D", "D. More people are insured by Medicare and Medicaid.", "The chart’s implication identified by the supplied answer key is that more people are insured by Medicare and Medicaid.", 15),
  makeQuestion(26, "battery-ss-26-27", choices.q26, "D", "D. Uninsured rates would be expected to drop as the economy improved and early provisions expanding coverage under the ACA went into effect.", "As the economy recovered and the Affordable Care Act began expanding coverage, the reasonable prediction was a decline in the uninsured rate.", 16),
  makeQuestion(27, "battery-ss-26-27", choices.q27, "B", "B. your payment and credit history", "The excerpt identifies payment and credit history as information found in a credit report.", 16),
  makeQuestion(28, "battery-ss-28-30", choices.q28, "C", "C. A lengthy trial", "The Sixth Amendment guarantees a speedy and public trial, not a lengthy trial.", 17),
  makeQuestion(29, "battery-ss-28-30", choices.q29, "B", "B. fair", "In this passage, impartial means fair or unbiased.", 17),
  makeQuestion(30, "battery-ss-28-30", choices.q30, "B", "B. A different location for the trial since it may be difficult to find an impartial jury in the area the crime was committed", "A change of venue moves a trial to another location when an impartial jury may be difficult to find in the original district.", 17),
  makeQuestion(31, "battery-ss-31", [], null, "Southeast", "The line showing De Soto’s route is located in the Southeast region of the United States.", 18),
  makeQuestion(32, "battery-ss-32-34", [], null, "More", "The chart shows more unemployed people with a high school diploma than with a bachelor’s degree.", 19),
  makeQuestion(33, "battery-ss-32-34", [], null, "Decreased", "The bar graph shows that the unemployment rate for people over 25 decreased in 2013 compared with 2012.", 19),
  makeQuestion(34, "battery-ss-32-34", choices.q34, "B", "B. Education plays a significant role in finding and keeping a job now and in the future.", "The data support a significant connection between education level and unemployment.", 19),
  makeQuestion(35, "battery-ss-35", choices.q35, "C", "C. a space shuttle", "The Challenger referred to in the document was a space shuttle.", 21),
  makeQuestion(36, "battery-ss-36", choices.q36, "C", "C. A graphic that correctly shows the listed wars and their increasing costs", "The correct graphic must represent the wars named in the paragraph and their rising costs; the supplied answer key marks C.", 22),
  makeQuestion(37, "battery-ss-37", choices.q37, "C", "C. no specific area, but all parts of the nation", "The lowest income category appears across different parts of the nation rather than one specific region.", 23),
  makeQuestion(38, "battery-ss-38-39", choices.q38, "C", "C. providing assistance after an earthquake in California", "Homeland Security responds to natural disasters in the United States, including earthquakes in California.", 26),
  makeQuestion(39, "battery-ss-38-39", choices.q39, "B", "B. an alert watchfulness", "Vigilance means alert watchfulness.", 26),
  makeQuestion(40, "battery-ss-40-41", choices.q40, "C", "C. Spanish America", "Spanish America shows the greatest increase in the chart and graph.", 27),
  makeQuestion(41, "battery-ss-40-41", choices.q41, "C", "C. Great Britain abolished slavery in all of its colonies.", "The supplied explanation attributes the sharp drop in British North America to Great Britain’s abolition of slavery in its colonies.", 27),
  makeQuestion(42, "battery-ss-42-43", choices.q42, "A", "A. He was unsure the Constitution allowed him to make the agreement.", "Jefferson was a strict interpreter of the Constitution and questioned whether it authorized acquiring new territory.", 29),
  makeQuestion(43, "battery-ss-42-43", choices.q43, "C", "C. The Federalists were concerned that more states would become Republican.", "The supplied answer key infers that Federalists feared the purchase would increase Republican power.", 29),
  makeQuestion(44, "battery-ss-44-46", choices.q44, "C", "C. temperance and abolition of slavery", "The passage says early suffrage leaders also championed temperance and abolition of slavery.", 30),
  makeQuestion(45, "battery-ss-44-46", [], null, "formed organizations, held meetings, went to the courts", "The supplied answer key identifies forming organizations, holding meetings, and going to the courts as the correct methods.", 30),
  makeQuestion(46, "battery-ss-44-46", choices.q46, "D", "D. Susan B. Anthony", "Susan B. Anthony attempted to vote in 1872 and was arrested, convicted, and fined.", 30),
  makeQuestion(47, "battery-ss-47", [], null, "D, A, C, B", "The sequence is: D, the break-in; A, cover-up steps; C, discovery of White House staff involvement; B, the Supreme Court case.", 31),
  makeQuestion(48, "battery-ss-48", choices.q48, "C", "C. his New Deal", "The quote refers to Roosevelt’s willingness to try methods associated with his New Deal.", 31),
  makeQuestion(49, "battery-ss-49", choices.q49, "B", "B. a writ of habeas corpus", "A writ of habeas corpus can be used to seek release from imprisonment without due process of law.", 31),
];
