import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, FileText, Image as ImageIcon } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { demoLessons } from "@/lib/lessonDemos";
import { completeSocialLessons } from "@/lib/completeSocialLessons";

type ReaderLesson = { id: string; subject: string; shortSubject: string; title: string; chapter: string; sourceStart: number; sourceEnd: number; sourceImages: string[]; focus: string; text?: string; practiceLabel?: string; accent: string };
const allReaderLessons: ReaderLesson[] = [
  ...demoLessons.map((lesson) => ({ ...lesson, sourceStart: lesson.sourcePage, sourceEnd: lesson.sourcePage, sourceImages: [lesson.sourceImage] })),
  ...completeSocialLessons.map((lesson) => ({ id: lesson.id, subject: lesson.chapter, shortSubject: lesson.title, title: lesson.title, chapter: lesson.chapter, sourceStart: lesson.sourcePages[0], sourceEnd: lesson.sourcePages[1], sourceImages: [...lesson.sourceImages], focus: `Study ${lesson.title} as a complete lesson from the McGraw Hill Social Studies review.`, text: lesson.teachingText, accent: lesson.accent, practiceLabel: `Practice ${lesson.title}` })),
];
const chapterOrder = ["Civics and Government", "U.S. History", "Economics", "Geography and the World"];

export default function LessonDemo() {
  const [, params] = useRoute("/lesson/:lessonId");
  const [, setLocation] = useLocation();
  const lesson = allReaderLessons.find((item) => item.id === params?.lessonId) || allReaderLessons[0];
  const currentIndex = allReaderLessons.findIndex((item) => item.id === lesson.id);
  const nextLesson = allReaderLessons[currentIndex + 1];
  const [sourceIndex, setSourceIndex] = useState(0);
  const isFullMcGrawLesson = Boolean(lesson.text);
  const sourceLabel = lesson.sourceStart === lesson.sourceEnd ? `Folio ${lesson.sourceStart}` : `Folios ${lesson.sourceStart}–${lesson.sourceEnd}`;
  const subjectSlug = "social-studies";

  return <div className="app-shell lesson-shell"><main className="main-canvas">
    <header className="topbar"><Link href="/" className="topbar-back"><ArrowLeft size={17} /> Study desk</Link><div className="breadcrumb"><span>Lessons</span><span className="slash">/</span><strong>{lesson.shortSubject}</strong></div><div className="topbar-actions"><span className="folio-label">{isFullMcGrawLesson ? `LESSON ${currentIndex - 4} / ${completeSocialLessons.length}` : `DEMO LESSON ${currentIndex + 1} / 4`}</span></div></header>
    <div className="content-wrap">
      <section className="lesson-hero" style={{ borderTopColor: lesson.accent }}><div className="eyebrow"><BookOpen size={15} /> {isFullMcGrawLesson ? "MCGRAW HILL LESSON" : "SOURCE-GROUNDED DEMO"}</div><div className="lesson-hero-grid"><div><span className="lesson-subject-chip" style={{ color: lesson.accent }}>{lesson.chapter}</span><h1>{lesson.title}</h1><p className="lesson-lede">{lesson.focus}</p><div className="lesson-meta"><span><FileText size={14} /> {sourceLabel}</span><span>{isFullMcGrawLesson ? "Complete lesson text" : "Demo lesson"}</span></div></div><div className="lesson-intent"><span className="eyebrow">LESSON METHOD</span><strong>Lesson first. Folios second.</strong><p>Read the teaching text as one lesson. Open the grouped source pages only when you want to inspect the original layout, table, map, graph, quotation, or figure.</p></div></div></section>
      <section className="lesson-text-section"><div className="section-heading"><div><div className="eyebrow"><BookOpen size={14} /> COMPLETE LESSON TEXT</div><h2>Read the idea in context.</h2></div><span className="lesson-source-label">{lesson.chapter}</span></div><p className="section-intro">This lesson is grouped by the workbook’s teaching heading, not split into one card per page.</p><article className="lesson-text-paper"><div className="lesson-text-intro"><span className="eyebrow">WHAT THIS LESSON TEACHES</span><p>{lesson.focus}</p></div><div className="lesson-prose">{(lesson.text || lesson.focus).split(/\n\s*\n/).filter((paragraph) => paragraph.trim()).map((paragraph, index) => <p key={`${lesson.id}-paragraph-${index}`}>{paragraph.trim()}</p>)}</div></article></section>
      <section className="lesson-source-section" aria-labelledby="lesson-source-title"><div className="section-heading"><div><div className="eyebrow"><ImageIcon size={14} /> OPTIONAL SOURCE FOLIOS</div><h2 id="lesson-source-title">Inspect the complete lesson pages.</h2></div><div className="lesson-source-controls"><button onClick={() => setSourceIndex((index) => Math.max(0, index - 1))} disabled={sourceIndex === 0} aria-label="Previous lesson source page"><ArrowLeft size={15} /></button><span>Page {sourceIndex + 1} / {lesson.sourceImages.length}</span><button onClick={() => setSourceIndex((index) => Math.min(lesson.sourceImages.length - 1, index + 1))} disabled={sourceIndex === lesson.sourceImages.length - 1} aria-label="Next lesson source page"><ArrowRight size={15} /></button></div></div><p className="section-intro">Every page belonging to this lesson remains available in order below. The image is bundled into the published app and does not depend on the teacher’s local folder.</p><figure className="lesson-folio-figure"><div className="lesson-folio-frame"><img src={lesson.sourceImages[sourceIndex]} alt={`${lesson.title}, source folio ${lesson.sourceStart + sourceIndex}`} /></div><figcaption><span>MCGRAW HILL EDUCATION / COMPLETE LESSON SOURCE</span><span>FOLIO {lesson.sourceStart + sourceIndex}</span></figcaption></figure></section>
      {isFullMcGrawLesson && <section className="lesson-index-section"><div className="section-heading"><div><div className="eyebrow">LESSON INDEX</div><h2>Continue lesson to lesson.</h2></div><span className="lesson-source-label">{completeSocialLessons.length} lessons in four chapters</span></div><div className="lesson-index-grid">{chapterOrder.map((chapter) => <div key={chapter} className="lesson-index-chapter"><strong>{chapter}</strong>{completeSocialLessons.filter((item) => item.chapter === chapter).map((item) => <Link key={item.id} href={`/lesson/${item.id}`} className={item.id === lesson.id ? "selected" : ""}>{item.title}<span>{item.sourcePages[0]}–{item.sourcePages[1]}</span></Link>)}</div>)}</div></section>}
      <section className="lesson-notes-grid"><article className="lesson-notes-card"><div className="eyebrow">STUDY ROUTINE</div><h2>Notice. Connect. Explain.</h2><p>Read the lesson text once without answering questions. Then inspect the grouped folios and explain which evidence, structure, or visual detail supports the main idea.</p><div className="lesson-reading-steps"><div><span>01</span><strong>Notice</strong><p>Find the central idea and the key terms.</p></div><div><span>02</span><strong>Connect</strong><p>Match the text to its source evidence.</p></div><div><span>03</span><strong>Explain</strong><p>Say the reasoning aloud before practice.</p></div></div></article><aside className="lesson-practice-card"><div className="eyebrow">NEXT STEP</div><CheckCircle2 size={25} style={{ color: lesson.accent }} /><h3>Practice this lesson.</h3><p>Open the Social Studies question library after studying the complete lesson and source folios.</p><button className="button-primary" onClick={() => setLocation(`/subject/${subjectSlug}`)}>{lesson.practiceLabel || "Open Social Studies practice"} <ArrowRight size={16} /></button></aside></section>
      <nav className="lesson-next-nav" aria-label="Lesson navigation"><Link href="/"><ArrowLeft size={15} /> Back to all lessons</Link>{nextLesson ? <Link href={`/lesson/${nextLesson.id}`}>Next lesson: {nextLesson.shortSubject}<ArrowRight size={15} /></Link> : <span>Lesson library complete</span>}</nav>
    </div><footer className="site-footer"><span>Bale Parvaaz GED</span><span>Lessons grouped around the source book.</span><span>Teacher Momeni · {sourceLabel}</span></footer>
  </main></div>;
}
